(function(_ds){var window=this;'use strict';var YU=function(a){var b=a.sp,c=a.Tm,d=a.Ll;a=a.vn;var f='<ul class="devsite-nav-list" role="navigation" aria-label="'+_ds.qp("\u76ee\u9304");f=f+'" scrollbars><li class="devsite-nav-item devsite-nav-heading devsite-toc-toggle" role="heading" aria-level="2"><a href="#top_of_page" class="devsite-nav-title" aria-label="'+_ds.qp("\u9801\u9762\u9802\u7aef");f=f+'" data-title="'+_ds.qp("\u9801\u9762\u9802\u7aef");f+='"><span class="devsite-nav-text">\u76ee\u9304</span></a>';c&&(f=f+'<button type="button" title="'+
_ds.qp("\u5c55\u958b/\u6536\u5408\u5167\u5bb9"),f+='" class="devsite-nav-show-all button-transparent material-icons"></button>');f+="</li>";for(var g=b.length,k=0;k<g;k++){var l=b[k];f+='<li class="devsite-nav-item"'+(c&&l.index<a?" visible":"")+'><a href="#'+_ds.Z(l.id)+'" class="devsite-nav-title gc-analytics-event" data-category="Site-Wide Custom Events" data-action="click" data-label="'+(c?"Embedded nav":"Right nav")+'" data-value="'+_ds.Z(k)+'" track-type="navigation" track-name="'+(c?"embeddedNav":
"rightNav")+'" track-metadata-position="'+_ds.Z(k)+'" track-metadata-link-destination="#'+_ds.Z(l.id)+'"><span class="devsite-nav-text" tooltip>'+_ds.Y(l.text)+"</span></a>";if(_ds.kp(l.children).length){f+='<ul class="devsite-nav-list">';l=l.children;for(var m=l.length,p=0;p<m;p++){var q=l[p];f+='<li class="devsite-nav-item"'+(c&&q.index<a?" visible":"")+'><a href="#'+_ds.Z(q.id)+'" class="devsite-nav-title gc-analytics-event" data-category="Site-Wide Custom Events" data-action="click" data-label="'+
(c?"Embedded nav":"Right nav")+'" data-value="'+_ds.Z(k)+"."+_ds.Z(p)+'" track-type="navigation" track-name="'+(c?"embeddedNav":"rightNav")+'" track-metadata-position="'+_ds.Z(k)+"."+_ds.Z(p)+'" track-metadata-link-destination="#'+_ds.Z(q.id)+'"><span class="devsite-nav-text" tooltip>'+_ds.Y(q.text)+"</span></a></li>"}f+="</ul>"}f+="</li>"}d&&(f=c?f+'<li class="devsite-nav-item devsite-apix-link"><a href="#try-it" class="devsite-nav-title"><span class="devsite-nav-text" tooltip>\u7acb\u5373\u8a66\u7528</span></a></li>':
f+'<button type="button" class="devsite-show-apix button-primary">\u8a66\u8a66\u770b\uff01</button>');c&&(f=f+'<li class="devsite-toc-toggle"><button type="button" class="button-flat devsite-nav-more-items material-icons" track-type="navigation" track-name="embeddedNavExpand" title="'+_ds.qp("\u5c55\u958b/\u6536\u5408\u5167\u5bb9"),f+='" aria-hidden="true"></button></li>');return(0,_ds.X)(f+"</ul>")},$U=function(){var a=_ds.U.call(this)||this;a.h=!1;a.C=!1;a.D=new _ds.Lj;a.L=[];a.N=0;a.F=[];a.J=new _ds.Ij(function(){return ZU(a)},
16);a.m=null;a.H=new _ds.Jl;a.o=new Set;a.G=[];a.j=null;return a},bV=function(a){var b,c,d;_ds.D(function(f){switch(f.h){case 1:if(!("IntersectionObserver"in _ds.Id())){f.K(2);break}a.m&&a.m.disconnect();b=document.querySelector("devsite-header");c=152;if(!b){f.K(3);break}return _ds.v(f,window.customElements.whenDefined("devsite-header"),4);case 4:(d=parseFloat(b.getAttribute("top-row--height")||0)+parseFloat(b.getAttribute("bottom-row--height")||0))&&(c=d);case 3:a.m=new IntersectionObserver(function(g){aV(a,
g)},{rootMargin:c+"px 0px 0px 0px",threshold:[0,1]});case 2:a.H.resolve(),_ds.x(f)}})},cV=function(a){_ds.Vg(a);a.dispatchEvent(new CustomEvent("devsite-element-hidden",{bubbles:!0}));a.removeAttribute("visible");a.setAttribute("hidden","");a.h||(a=document.querySelector(".devsite-main-content"))&&a.removeAttribute("has-toc")},dV=function(a){a.dispatchEvent(new CustomEvent("devsite-element-visible",{bubbles:!0}));a.removeAttribute("hidden");a.setAttribute("visible","");if(!a.h){var b=document.querySelector(".devsite-main-content");
b&&b.setAttribute("has-toc","");bV(a)}},ZU=function(a){if(!a.hasAttribute("disabled")){var b=document.querySelector("devsite-content .devsite-article-body");b?(a.h?a.classList.add("devsite-toc-embedded"):a.classList.add("devsite-toc"),eV(a,b),a.C=!0,a.h||(fV(a),gV(a))):cV(a)}},eV=function(a,b){var c,d,f,g;_ds.D(function(k){c=[];d=!1;f=Array.from(b.querySelectorAll("h2:not(.hide-from-toc):not(#contents):not(#table-of-contents), h3:not(.hide-from-toc):not(#contents):not(#table-of-contents)")).filter(function(l){return l.id&&
l.dataset.text}).filter(function(l){return hV(l)});f.forEach(function(l,m){l={id:l.id,level:l.tagName.toLowerCase(),text:l.dataset.text,children:[],index:m};"h2"===l.level?(c.push(l),d=!0):d?c[c.length-1].children.push(l):c.push(l)});if((g=_ds.Lb(a.F,c,a.ai.bind(a)))&&a.C)return k.return();c.length?(iV(a,c),dV(a),a.h||jV(a,f)):cV(a);a.F=c;a.h||(fV(a),gV(a),a.dispatchEvent(new CustomEvent("devsite-toc-updated",{bubbles:!0})));_ds.x(k)})},aV=function(a,b){b=_ds.t(b);for(var c=b.next();!c.done;c=b.next())c=
c.value,c.isIntersecting?a.o.add(c.target):a.o.delete(c.target);if(b=a.o.values().next().value){var d="#"+b.id,f="#"+encodeURI(b.id);b=a.G.find(function(g){g=g.href;return-1!==g.indexOf(d,g.length-d.length)||-1!==g.indexOf(f,g.length-f.length)});a.j!==b&&(a.j&&a.j.classList.remove("devsite-nav-active"),b&&(b.classList.add("devsite-nav-active"),a.j=b))}},jV=function(a,b){var c,d,f;_ds.D(function(g){if(1==g.h)return _ds.v(g,a.H.promise,2);if(!a.m)return g.return();a.m.disconnect();a.o.clear();a.j&&
a.j.classList.remove("devsite-nav-active");a.j=null;c=_ds.t(b);for(d=c.next();!d.done;d=c.next())f=d.value,a.m.observe(f);_ds.x(g)})},hV=function(a){return _ds.Pv.find(function(b){return!!_ds.zh(a,b,6)})||_ds.yh(a,"devsite-selector",null,6)||_ds.zh(a,"devsite-dialog",3)?!1:!0},iV=function(a,b){var c=_ds.Zp(YU,{sp:b,Tm:a.h,Ll:!!document.body.querySelector("devsite-apix, .devsite-apix"),vn:5});a.G=Array.from(c.querySelectorAll(".devsite-nav-title"));_ds.Vg(a);a.h&&c.setAttribute("hidden","");a.appendChild(c);
a.h&&(8<=a.getElementsByClassName("devsite-nav-item").length&&(Array.from(a.querySelectorAll(".devsite-nav-show-all, .devsite-nav-more-items")).forEach(function(d){a.D.listen(d,"click",function(){a.hasAttribute("expanded")?a.removeAttribute("expanded"):a.setAttribute("expanded","")})}),a.setAttribute("expandable","")),setTimeout(function(){c.removeAttribute("hidden")},0))},gV=function(a){var b=a.getAttribute("offset")||0;(a=a.querySelector(".devsite-nav-list"))&&_ds.Uj(a,"transform","translate3d(0, -"+
b+"px, 0)")},fV=function(a){var b=a.getAttribute("max-height")||0;(a=a.querySelector(".devsite-nav-list"))&&_ds.Uj(a,"max-height",b+"px")};_ds.u($U,_ds.U);_ds.e=$U.prototype;_ds.e.connectedCallback=function(){var a=this;this.h=this.hasAttribute("devsite-toc-embedded");ZU(this);this.D.listen(document.body,"devsite-content-updated",function(){ZU(a)})};_ds.e.disconnectedCallback=function(){cV(this);this.C=!1;_ds.Rj(this.D)};_ds.e.attributeChangedCallback=function(a){switch(a){case "offset":gV(this);break;case "max-height":fV(this)}};
_ds.e.renderUpdatedContent=function(a){a=a&&"false"===a.toLowerCase();this.F=[];_ds.Vg(this);a?(this.setAttribute("disabled",""),cV(this)):(this.removeAttribute("disabled"),dV(this),this.J.qa())};_ds.e.ai=function(a,b){var c=!0;if(a.children.length||b.children.length)c=_ds.Lb(a.children,b.children,this.ai.bind(this));return c&&a.id===b.id&&a.text===b.text};_ds.n.Object.defineProperties($U,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return["max-height","offset"]}}});
$U.prototype.renderUpdatedContent=$U.prototype.renderUpdatedContent;$U.prototype.attributeChangedCallback=$U.prototype.attributeChangedCallback;$U.prototype.disconnectedCallback=$U.prototype.disconnectedCallback;$U.prototype.connectedCallback=$U.prototype.connectedCallback;try{window.customElements.define("devsite-toc",$U)}catch(a){console.warn("devsite.app.customElement.DevsiteToc",a)};})(_ds_www);
