(function(_ds){var window=this;'use strict';var mQ=function(a){var b=arguments.length;if(1==b&&Array.isArray(arguments[0]))return mQ.apply(null,arguments[0]);for(var c={},d=0;d<b;d++)c[arguments[d]]=!0;return c},nQ=function(a,b,c,d,f,g,k,l,m,p){this.h=a;this.C=b;this.G=c;this.m=d;this.o=f;this.D=g;this.F=k;this.H=l;this.j=m;this.J=p},oQ=function(a){return new nQ(a.m,a.o,a.H,a.h,a.j,a.C,a.J,a.F,a.D,a.G)},pQ=function(a,b){a.G=b;return a},qQ=function(a,b){a.D=b;return a},rQ=function(a,b){a.F=b;return a},sQ=function(){this.m=null;
this.o="";this.G=this.D=this.F=this.J=this.C=this.j=this.h=this.H=null},tQ=function(a){var b=a.Z;b=(b=b&&"composed"in b&&b&&"composedPath"in b&&b.composed&&b.composedPath())&&0<b.length?b[0]:a.target;return oQ(pQ(qQ(rQ((new sQ).keyCode(a.keyCode||0).key(a.key||"").shiftKey(!!a.shiftKey).altKey(!!a.altKey).ctrlKey(!!a.ctrlKey).metaKey(!!a.metaKey).target(a.target),b),function(){return a.preventDefault()}),function(){return a.stopPropagation()}))},uQ=function(a){this.h=a||null;this.next=a?null:{}},
vQ=function(a,b){var c=b.shift();_ds.fd(c,function(d){var f=a[d];f&&(0==b.length?f.h&&delete a[d]:f.next&&(vQ(f.next,b.slice(0)),_ds.Xb(f.next)&&delete a[d]))})},yQ=function(a){a=a.replace(/[ +]*\+[ +]*/g,"+").replace(/[ ]+/g," ").toLowerCase();a=a.split(" ");for(var b=[],c,d=0;c=a[d];d++){var f=c.split("+"),g=null,k=null;c=0;for(var l,m=0;l=f[m];m++){switch(l){case "shift":c|=1;continue;case "ctrl":c|=2;continue;case "alt":c|=4;continue;case "meta":c|=8;continue}f=void 0;g=l;if(!wQ){k={};for(f in xQ)k[xQ[f]]=
_ds.eq(parseInt(f,10));wQ=k}k=wQ[g];g=l;break}b.push({key:g,keyCode:k,modifiers:c})}return b},zQ=function(a,b,c){c=c||0;b=["c_"+b+"_"+c];""!=a&&b.push("n_"+a+"_"+c);return b},AQ=function(a,b){if("string"===typeof b[a])a=_ds.Nb(yQ(b[a]),function(f){return zQ(f.key||"",f.keyCode,f.modifiers)});else{var c=b,d=a;Array.isArray(b[a])&&(c=b[a],d=0);for(a=[];d<c.length;d+=2)a.push(zQ("",c[d],c[d+1]))}return a},BQ=function(a,b){32==a.D&&32==b.h&&(0,b.j)();a.D=null},CQ=function(a){return _ds.gv&&a.o&&a.m},
DQ=function(a,b,c){var d=b.shift();_ds.fd(d,function(f){if((f=a[f])&&(0==b.length||f.h))throw Error("Keyboard shortcut conflicts with existing shortcut");});b.length?_ds.fd(d,function(f){f=f.toString();var g=new uQ;f=f in a?a[f]:a[f]=g;DQ(f.next,b.slice(0),c)}):_ds.fd(d,function(f){a[f]=new uQ(c)})},EQ=function(a,b){for(var c=0;c<b.length;c++){var d=a[b[c]];if(d)return d}},FQ=function(a,b,c){for(;0<c.length&&b;){var d=c.shift();if((d=EQ(b,d))&&(0==c.length&&d.h||FQ(a,d.next,c.slice(0))))return!0}return!1},
GQ=function(a,b,c){_ds.Pf.call(this,a,c);this.j=b},HQ=function(a,b,c){a:{var d=b.h;if(""!=b.C){var f=b.C;if("Control"==f||"Shift"==f||"Meta"==f||"AltGraph"==f){d=!1;break a}}else if(16==d||17==d||18==d){d=!1;break a}f=b.H;var g="TEXTAREA"==f.tagName||"INPUT"==f.tagName||"BUTTON"==f.tagName||"SELECT"==f.tagName,k=!g&&(f.isContentEditable||f.ownerDocument&&"on"==f.ownerDocument.designMode);d=!g&&!k||a.L[d]||a.F?!0:k?!1:a.N&&(b.m||b.o||b.D)?!0:"INPUT"==f.tagName&&a.W[f.type]?13==d:"INPUT"==f.tagName||
"BUTTON"==f.tagName?a.O?!0:32!=d:!1}if(d)if(!c&&CQ(b))a.o=!1;else{c=_ds.eq(b.h);d=zQ(b.C,c,(b.G?1:0)|(b.o?2:0)|(b.m?4:0)|(b.D?8:0));f=EQ(a.m,d);if(!f||1500<=_ds.xb()-a.C)a.m=a.j,a.C=_ds.xb();(f=EQ(a.m,d))&&f.next&&(a.m=f.next,a.C=_ds.xb());f&&(f.next?(0,b.j)():(a.m=a.j,a.C=_ds.xb(),a.G&&(0,b.j)(),a.J&&(0,b.J)(),d=f.h,f=a.dispatchEvent(new GQ("shortcut",d,b.F)),(f&=a.dispatchEvent(new GQ("shortcut_"+d,d,b.F)))||(0,b.j)(),_ds.Wj&&(a.D=c)))}},KQ=function(a){_ds.Zi.call(this);this.m=this.j={};this.C=
0;this.L=mQ(IQ);this.W=mQ(JQ);this.G=!0;this.F=this.J=!1;this.N=!0;this.O=!1;this.D=null;this.h=a;_ds.cg(this.h,"keydown",this.Li,void 0,this);_ds.cg(this.h,"synthetic-keydown",this.Qi,void 0,this);_ds.gv&&(_ds.cg(this.h,"keypress",this.Si,void 0,this),_ds.cg(this.h,"synthetic-keypress",this.Ti,void 0,this));_ds.cg(this.h,"keyup",this.Mi,void 0,this);_ds.cg(this.h,"synthetic-keyup",this.Ri,void 0,this)},LQ=function(a,b){return _ds.P(a,10,b||[])},MQ=function(a){return(0,_ds.X)('<div class="devsite-popout" id="'+
_ds.Z(a.id)+'"><div class="devsite-popout-result devsite-suggest-results-container" devsite-hide></div></div>')},NQ=function(a){a=a||{};var b='<button type="submit" class="button button-white devsite-search-project-scope">';a="All results in "+_ds.Y(a.Ya);return(0,_ds.X)(b+a+"</button>")},OQ=function(a){var b=a.query,c=a.lc,d='<button type="submit" class="button button-white devsite-suggest-all-results">';a.Xb?(a="All results across "+_ds.Y(c),d+=a):(a='All results for "'+(_ds.Y(b)+'"'),d+=a);return(0,_ds.X)(d+
"</button>")},PQ=function(a){var b=a.link,c=a.title,d=a.public,f=a.action,g=a.Vj,k=a.Ya,l=a.Xb;a=a.rg;b=(d?"":'<devsite-analytics-scope action="'+_ds.Z(_ds.Op("Restricted "+f))+'">')+'<a class="devsite-result-item-link" href="'+_ds.Z(_ds.Op(b))+'"><span class="devsite-suggestion-fragment">'+_ds.Y(c)+"</span>"+(a?'<span class="devsite-suggestion-fragment">'+_ds.Y(a)+"</span>":"")+(g?'<span class="devsite-suggestion-fragment">'+_ds.Y(g)+"</span>":"")+(_ds.mp(k)&&!l?'<span class="devsite-suggestion-fragment">'+
_ds.Y(k)+"</span>":"");d||(b+='<span class="devsite-result-item-confidential">Confidential</span>');return(0,_ds.X)(b+("</a>"+(d?"":"</devsite-analytics-scope>")))},QQ=function(a){var b=a.Ya,c=a.Xb,d=a.query,f=a.$j;a=a.lc;b='<div class="devsite-suggest-wrapper '+(f?"":"devsite-search-disabled")+'"><div class="devsite-suggest-section"><div class="devsite-result-label">There are no suggestions for your query</div></div>'+((f?'<div class="devsite-suggest-footer">'+(c?NQ({Ya:b}):"")+OQ({Xb:c,query:d,
lc:a})+"</div>":"")+"</div>");return(0,_ds.X)(b)},RQ=function(a){var b=a.$n,c=a.zo,d=a.Go,f=a.Ya,g=a.Xb,k=a.query,l=a.Lo,m=a.$j;a=a.lc;var p='<div class="devsite-suggest-wrapper '+(m?"":"devsite-search-disabled")+'" tabindex="0" role="list"><div class="devsite-suggest-section">';if(0<d.length){p=p+'<div class="devsite-suggest-sub-section" role="listitem"><div class="devsite-suggest-header" id="devsite-suggest-header-partial-query" role="heading" aria-level="2">Suggested searches'+((g?'<span class="devsite-suggest-project">'+
_ds.Y(f)+"</span>":"")+'</div><devsite-analytics-scope category="Site-Wide Custom Events" label="Search" role="list" aria-labelledby="devsite-suggest-header-partial-query" action="Query Suggestion Click">');for(var q=d.length,r=0;r<q;r++){var w=d[r];p+='<div class="devsite-result-item devsite-nav-label" id="suggestion-partial-query-'+_ds.Z(r)+'" role="listitem" index=":'+_ds.Z(r)+'">'+PQ({link:_ds.O(w,2),title:w.Ea(),public:_ds.tf(w,14),action:"Query Suggestion Click"})+"</div>"}p+="</devsite-analytics-scope></div>"}p+=
0<d.length&&0<b.length?'<hr role="none">':"";if(0<b.length){p=p+'<div class="devsite-suggest-sub-section" role="listitem"><div class="devsite-suggest-header" id="devsite-suggest-header-product" role="heading" aria-level="2">Pages'+((g?'<span class="devsite-suggest-project">'+_ds.Y(f)+"</span>":"")+'</div><devsite-analytics-scope category="Site-Wide Custom Events" label="Search" role="list" aria-labelledby="devsite-suggest-header-product" action="Page Suggestion Click">');q=b.length;for(r=0;r<q;r++)w=
b[r],p+='<div class="devsite-result-item devsite-nav-label" id="suggestion-product-'+_ds.Z(r)+'" role="listitem" index=":'+_ds.Z(r)+'">'+PQ({link:_ds.O(w,2),title:w.Ea(),public:_ds.tf(w,14),Ya:_ds.O(w,4),Xb:g,action:"Page Suggestion Click"})+"</div>";p+="</devsite-analytics-scope></div>"}p+=0<l.length&&0<b.length+d.length?'<hr role="none">':"";if(0<l.length){p=p+'<div class="devsite-suggest-sub-section" role="listitem"><div class="devsite-suggest-header" id="devsite-suggest-header-reference" role="heading" aria-level="2">Reference'+
((g?'<span class="devsite-suggest-project">'+_ds.Y(f)+"</span>":"")+'</div><devsite-analytics-scope category="Site-Wide Custom Events" label="Search" role="list" aria-labelledby="devsite-suggest-header-reference" action="Reference Suggestion Click">');q=l.length;for(r=0;r<q;r++)w=l[r],p+='<div class="devsite-result-item devsite-nav-label" id="suggestion-reference-'+_ds.Z(r)+'" role="listitem" index=":'+_ds.Z(r)+'">'+PQ({link:_ds.O(w,2),title:w.Ea(),public:_ds.tf(w,14),action:"Reference Suggestion Click",
Vj:_ds.O(w,3),Ya:_ds.O(w,4),Xb:g,rg:_ds.L(w,10)[0]})+"</div>";p+="</devsite-analytics-scope></div>"}p+=0<c.length&&0<b.length+d.length+l.length?'<hr role="none">':"";if(0<c.length){p+='<div class="devsite-suggest-sub-section" role="listitem"><div class="devsite-suggest-header" id="devsite-suggest-header-other-products" role="heading" aria-level="2"><span role="columnheader">Products</span></div><devsite-analytics-scope category="Site-Wide Custom Events" label="Search" role="list" aria-labelledby="devsite-suggest-header-other-products" action="Product Suggestion Click">';
b=c.length;for(d=0;d<b;d++)l=c[d],p+='<div class="devsite-result-item devsite-nav-label" id="suggestion-other-products-'+_ds.Z(d)+'" role="listitem" index=":'+_ds.Z(d)+'">'+PQ({link:_ds.O(l,2),title:l.Ea(),public:_ds.tf(l,14),action:"Product Suggestion Click"})+"</div>";p+="</devsite-analytics-scope></div>"}p+="</div>"+(m?'<div class="devsite-suggest-footer">'+(g?NQ({Ya:f}):"")+OQ({Xb:g,query:k,lc:a})+"</div>":"")+"</div>";return(0,_ds.X)(p)},SQ=function(){var a=_ds.U.call(this)||this;a.J=!1;a.H=
{};a.G="";a.C=null;a.j=new _ds.Lj;a.h=null;return a},XQ=function(a){a.h&&(a.j.listen(a.h,"suggest-service-search",function(b){a:{var c=a.D.querySelector(".highlight");if(c&&(c=c.querySelector(".devsite-result-item-link"))){c.click();break a}TQ(a,b.detail.originalEvent,!!a.C)}}),a.j.listen(a.h,"suggest-service-suggestions-received",function(b){return void UQ(a,b)}),a.j.listen(a.h,"suggest-service-focus",function(){VQ(a,!0)}),a.j.listen(a.h,"suggest-service-blur",function(){VQ(a,!1)}),a.j.listen(a.h,
"suggest-service-input",function(){!a.H["Text Entered Into Search Bar"]&&a.h.query.trim()&&(a.dispatchEvent(new CustomEvent("devsite-analytics-observation",{detail:{category:"Site-Wide Custom Events",label:"Search",action:"Text Entered Into Search Bar"},bubbles:!0})),a.H["Text Entered Into Search Bar"]=!0)}),a.j.listen(a.h,"suggest-service-navigate",function(b){return void WQ(a,b)}),a.j.listen(document.body,"devsite-page-changed",function(){return a.H={}}),a.h.fk("SLASH",191));a.m&&a.j.listen(a.m,
"submit",function(b){TQ(a,b)});a.D&&a.j.listen(a.D,"click",function(b){var c=b.target;"A"==c.tagName.toUpperCase()&&VQ(a,!1);c.classList.contains("devsite-search-project-scope")&&TQ(a,b,!0)});a.N&&a.j.listen(a.N,"click",function(){return void VQ(a,!0)});a.L&&a.j.listen(a.L,"click",function(){return void VQ(a,!1)})},TQ=function(a,b,c){c=void 0===c?!1:c;var d,f;_ds.D(function(g){if(1==g.h){b.preventDefault();b.stopPropagation();if(!a.hasAttribute("enable-search"))return g.K(0);a.H["Full Site Search"]||
(a.dispatchEvent(new CustomEvent("devsite-analytics-observation",{detail:{category:"Site-Wide Custom Events",label:"Search",action:"Full Site Search"},bubbles:!0})),a.H["Full Site Search"]=!0);d=c&&a.C?_ds.Bi(a.C):_ds.Bi(a.m.getAttribute("action"));f=new _ds.Xh(d.href);_ds.ji(f,"q",a.h.query);d.search=f.h.toString();return _ds.v(g,DevsiteApp.fetchPage(d.href),3)}VQ(a,!1);_ds.x(g)})},WQ=function(a,b){var c=b.detail;b=a.o.querySelector(".highlight");var d,f=Array.from(a.o.querySelectorAll(".devsite-result-item")),
g=[],k=-1;if(b){var l=_ds.xh(b,function(p){return p.classList.contains("devsite-suggest-section")});g=Array.from(l.querySelectorAll(".devsite-result-item"));l=_ds.ch(b.parentNode.parentNode);var m=_ds.dh(b.parentNode.parentNode);k=f.indexOf(b)}switch(c.keyCode){case 37:if(!l&&!m)return;b&&(c=b.getAttribute("index"),m?(d=m.querySelector('[index="'+c+'"]'))||(d=_ds.Cb(Array.from(m.querySelectorAll("[index]")))):l&&((d=l.querySelector('[index="'+c+'"]'))||(d=_ds.Cb(Array.from(l.querySelectorAll("[index]"))))));
break;case 39:if(!l&&!m)return;b&&(c=b.getAttribute("index"),l?(d=l.querySelector('[index="'+c+'"]'))||(d=_ds.Cb(Array.from(l.querySelectorAll("[index]")))):m&&((d=m.querySelector('[index="'+c+'"]'))||(d=_ds.Cb(Array.from(m.querySelectorAll("[index]"))))));break;case 38:b?(d=f[k-1])||(d=_ds.Cb(g)):d=_ds.Cb(f);break;case 40:b?(d=f[k+1])||(d=g[0]):d=f[0]}b&&(b.classList.remove("highlight"),b.removeAttribute("aria-selected"));d&&(a.F.setAttribute("aria-activedescendant",d.id),d.setAttribute("aria-selected",
"true"),d.classList.add("highlight"),d.scrollIntoViewIfNeeded&&d.scrollIntoViewIfNeeded()||d.scrollIntoView())},VQ=function(a,b){if(a.J!==b){_ds.kq(a.h,b);if(a.J=b)a.setAttribute("search-active","");else{var c=a.D.querySelector(".highlight");c&&c.classList.remove("highlight");a.removeAttribute("search-active");a.setAttribute("aria-expanded","false");_ds.Vg(a.o)}a.hasAttribute("capture")||a.dispatchEvent(new CustomEvent("devsite-search-toggle",{detail:{active:b},bubbles:!0}))}},UQ=function(a,b){b=
b.detail;var c=b.suggestions;b=b.query;if(a.h.query.toLowerCase().startsWith(b.toLowerCase()))if(c){var d=c.ob();c=d.filter(function(z){return 2===z.Sb()});var f=d.filter(function(z){return 3===z.Sb()}),g=d.filter(function(z){return 4===z.Sb()}).slice(0,5),k=d.filter(function(z){return 1===z.Sb()});d=c.length+g.length+k.length;var l=a.C?a.C:"";g.forEach(function(z){return z.Cc(_ds.Bi(l+"/s/results/?q="+z.Ea()).toString())});var m=b.split(YQ);f.forEach(function(z){return LQ(z,_ds.L(z,10).filter(function(C){return m.some(function(F){return C.includes(F)})}))});
var p=a.getAttribute("project-name")||"",q=a.hasAttribute("project-scope"),r=a.hasAttribute("enable-search"),w=a.getAttribute("tenant-name")||"";c={$n:c,Ya:p,Xb:q,zo:k,Go:g,query:b,Lo:f,$j:r,lc:w};0===d?_ds.Wp(a.o,QQ,c):(_ds.Wp(a.o,RQ,c),ZQ(a,b));a.setAttribute("aria-expanded","true");a.o.removeAttribute("hidden")}else a.o.setAttribute("hidden",""),a.setAttribute("aria-expanded","false")},ZQ=function(a,b){b=new RegExp("("+_ds.Nd(b)+")","ig");a=_ds.t(a.o.querySelectorAll(".devsite-suggestion-fragment"));
for(var c=a.next();!c.done;c=a.next()){c=c.value;var d=c.innerHTML;d=d.replace(b,"<b>$1</b>");d=_ds.Ls(d);_ds.Dd(c,d)}},xQ={8:"backspace",9:"tab",13:"enter",16:"shift",17:"ctrl",18:"alt",19:"pause",20:"caps-lock",27:"esc",32:"space",33:"pg-up",34:"pg-down",35:"end",36:"home",37:"left",38:"up",39:"right",40:"down",45:"insert",46:"delete",48:"0",49:"1",50:"2",51:"3",52:"4",53:"5",54:"6",55:"7",56:"8",57:"9",59:"semicolon",61:"equals",65:"a",66:"b",67:"c",68:"d",69:"e",70:"f",71:"g",72:"h",73:"i",74:"j",
75:"k",76:"l",77:"m",78:"n",79:"o",80:"p",81:"q",82:"r",83:"s",84:"t",85:"u",86:"v",87:"w",88:"x",89:"y",90:"z",93:"context",96:"num-0",97:"num-1",98:"num-2",99:"num-3",100:"num-4",101:"num-5",102:"num-6",103:"num-7",104:"num-8",105:"num-9",106:"num-multiply",107:"num-plus",109:"num-minus",110:"num-period",111:"num-division",112:"f1",113:"f2",114:"f3",115:"f4",116:"f5",117:"f6",118:"f7",119:"f8",120:"f9",121:"f10",122:"f11",123:"f12",186:"semicolon",187:"equals",189:"dash",188:",",190:".",191:"/",
192:"`",219:"open-square-bracket",220:"\\",221:"close-square-bracket",222:"single-quote",224:"win"};_ds.e=sQ.prototype;_ds.e.keyCode=function(a){this.m=a;return this};_ds.e.key=function(a){this.o=a;return this};_ds.e.shiftKey=function(a){this.H=a;return this};_ds.e.altKey=function(a){this.h=a;return this};_ds.e.ctrlKey=function(a){this.j=a;return this};_ds.e.metaKey=function(a){this.C=a;return this};_ds.e.target=function(a){this.J=a;return this};
var IQ=[27,112,113,114,115,116,117,118,119,120,121,122,123,19],JQ="color date datetime datetime-local email month number password search tel text time url week".split(" "),wQ;_ds.E(GQ,_ds.Pf);_ds.E(KQ,_ds.Zi);_ds.e=KQ.prototype;_ds.e.jF=function(){return this.G};_ds.e.xfa=function(a){this.J=a};_ds.e.kF=function(){return this.J};_ds.e.ufa=function(a){this.F=a};_ds.e.gF=function(){return this.F};_ds.e.Jja=function(a){this.N=a};_ds.e.zJ=function(){return this.N};_ds.e.wfa=function(a){this.O=a};
_ds.e.Wj=_ds.ca(4);_ds.e.Dna=function(a){vQ(this.j,AQ(0,arguments))};_ds.e.wX=function(a){return FQ(this,this.j,AQ(0,arguments))};_ds.e.Xha=function(a){this.L=mQ(a)};_ds.e.YH=function(){return _ds.Wb(this.L)};
_ds.e.ea=function(){KQ.ua.ea.call(this);this.j={};_ds.ng(this.h,"keydown",this.Li,!1,this);_ds.ng(this.h,"synthetic-keydown",this.Qi,!1,this);_ds.gv&&(_ds.ng(this.h,"keypress",this.Si,!1,this),_ds.ng(this.h,"synthetic-keypress",this.Ti,!1,this));_ds.ng(this.h,"keyup",this.Mi,!1,this);_ds.ng(this.h,"synthetic-keyup",this.Ri,!1,this);this.h=null};_ds.e.iO=function(a){return"shortcut_"+a};_ds.e.Mi=function(a){a=tQ(a);_ds.Wj&&BQ(this,a);_ds.gv&&!this.o&&CQ(a)&&HQ(this,a,!0)};
_ds.e.Ri=function(a){a=a.j();_ds.Wj&&BQ(this,a);_ds.gv&&!this.o&&CQ(a)&&HQ(this,a,!0)};_ds.e.Si=function(a){a=tQ(a);32<a.h&&CQ(a)&&(this.o=!0)};_ds.e.Ti=function(a){a=a.j();32<a.h&&CQ(a)&&(this.o=!0)};_ds.e.Li=function(a){HQ(this,tQ(a))};_ds.e.Qi=function(a){HQ(this,a.j())};
_ds.lq.prototype.fk=_ds.ea(5,function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];var f=this;this.j&&this.j.dispose();a&&(this.j=new KQ(document),this.j.G=!1,this.j.Wj.apply(this.j,[a].concat(_ds.pa(c))),this.eventHandler.listen(this.j,"shortcut",function(g){var k=document;k.activeElement&&k.activeElement===k.body&&(g.preventDefault(),_ds.kq(f,!0))}))});KQ.prototype.Wj=_ds.ea(4,function(a,b){DQ(this.j,AQ(1,arguments),a)});var YQ=/[ .()<>{}\[\]\/:,]+/,$Q=0;_ds.u(SQ,_ds.U);SQ.prototype.disconnectedCallback=function(){_ds.Rj(this.j);this.h&&(this.h.dispose(),this.h=null)};SQ.prototype.attributeChangedCallback=function(a,b,c){switch(a){case "project-scope":this.G=c||"";this.h&&(this.h.N=this.G);break;case "url-scoped":this.C=c;break;case "disabled":this.F&&(this.F.disabled=null!==c)}};
SQ.prototype.connectedCallback=function(){if(this.m=this.querySelector("form")){this.F=this.m.querySelector(".devsite-search-query");this.N=this.m.querySelector(".devsite-search-button[search-open]");this.L=this.querySelector(".devsite-search-button[search-close]");var a="devsite-search-popout-container-id-"+ ++$Q;this.F.setAttribute("aria-controls",a);this.D=_ds.Zp(MQ,{id:a});this.o=this.D.querySelector(".devsite-suggest-results-container");this.m.appendChild(this.D);this.hasAttribute("project-scope")&&
(this.G=this.getAttribute("project-scope"));this.hasAttribute("url-scoped")&&(this.C=this.getAttribute("url-scoped"));this.m&&this.F&&(this.h=new _ds.lq(this.m,this.F),this.h.m=!0,this.h.If=this.hasAttribute("enable-query-completion"),this.h.fe=!0,this.h.Hf=!0,this.h.Jf=!0,this.h.N=this.G,this.h.m=this.hasAttribute("enable-suggestions"));XQ(this)}};_ds.n.Object.defineProperties(SQ,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return["project-scope","url-scoped","disabled"]}}});
SQ.prototype.connectedCallback=SQ.prototype.connectedCallback;SQ.prototype.attributeChangedCallback=SQ.prototype.attributeChangedCallback;SQ.prototype.disconnectedCallback=SQ.prototype.disconnectedCallback;try{window.customElements.define("devsite-search",SQ)}catch(a){console.warn("devsite.app.customElement.DevsiteSearch",a)};})(_ds_www);
