(function(_ds){var window=this;'use strict';var uU=function(a){var b=a.Kg,c='<div class="dropdown-tabbed-menu"><ul class="dropdown-tabbed-menu-list">';a=a.Kl;for(var d=a.length,f=0;f<d;f++){var g=a[f];c+='<li class="dropdown-tabbed-menu-list-item"><a href="#" column-id="'+_ds.Z(g.$h)+'" tabindex="0" track-type="navMenu" track-metadata-eventdetail="'+_ds.Z(g.text)+'" track-name="'+_ds.Z(b)+'" track-metadata-href="#'+_ds.Z(g.$h)+'" track-metadata-position="nav - secondary" track-metadata-module_headline="'+_ds.Z(b)+'">'+_ds.Y(g.text)+
"</a></li>"}return(0,_ds.X)(c+"</ul></div>")},vU=function(a){var b=a.Kg,c=a.href;a=a.text;return(0,_ds.X)('<div class="dropdown-tabbed-menu-button"><a href="'+_ds.Z(_ds.Op(c))+'" track-type="navMenu" track-name="'+_ds.Z(b)+'" track-metadata-eventdetail="'+_ds.Z(a)+'" track-metadata-href="'+_ds.Z(c)+'" track-metadata-position="nav - secondary" track-metadata-module_headline="'+_ds.Z(b)+'">'+_ds.Y(a)+"</a></div>")},xU=function(){var a=_ds.U.call(this)||this;a.H=null;a.G=!1;a.j=new _ds.Lj;a.m=new _ds.Lj;
a.h=null;a.N=null;a.C=null;a.D=null;a.L=0;a.o=[];a.F=0;a.J=new _ds.Ij(function(){wU(a)},20);return a},EU=function(a){a.j.listen(document.body,"devsite-sticky-resize",function(){return a.J.qa()});a.j.listen(a,"click",function(f){if(!(f.shiftKey||f.ctrlKey||f.metaKey||f.altKey)){var g=f.target,k=yU(a,g);if(k)if(k===a.h)zU(a,f);else if(AU(a),g.classList.contains("devsite-tabs-dropdown-toggle"))f.preventDefault(),f.stopPropagation(),k.hasAttribute("dropdown--open")?BU(a):CU(a,k);else{var l;"A"===g.tagName?
l=g:l=_ds.yh(g,"A");var m=k.querySelector(".devsite-tabs-dropdown");if(m&&m.contains(g))l&&l.hasAttribute("href")||(f.preventDefault(),f.stopPropagation());else{if(f=a.H||a.querySelector("[active]"))f.removeAttribute("active"),f.setAttribute("aria-selected","false");k.setAttribute("active","");k.setAttribute("aria-selected","true");a.H=k;l&&l&&"#"!==l.href||a.J.qa()}}}});if(a.querySelector("tab[dropdown]")||a.querySelector("tab[overflow-tab]")){var b="onpointermove"in window?"pointerover":"mouseover",
c="onpointermove"in window?"pointerleave":"mouseleave",d=a.querySelectorAll("tab[clickable]");if(d.length){b=_ds.t(d);for(c=b.next();!c.done;c=b.next())a.j.listen(c.value,"click",function(f){var g=f.target,k=yU(a,g),l=k.querySelector(".devsite-tabs-dropdown");!l||a.h.contains(g)||l.contains(g)||(f.preventDefault(),f.stopPropagation(),k.hasAttribute("dropdown--open")?BU(a):DU(a,f))});a.j.listen(document.body,"click",function(f){a.D.contains(f.target)||BU(a)})}else a.j.listen(a,[b,"focusin"],function(f){document.body.hasAttribute("touch")||
DU(a,f)}),a.j.listen(a,[c,"focusout"],function(){document.body.hasAttribute("touch")||BU(a,300)})}Array.from(a.querySelectorAll(".devsite-tabs-close-button")).forEach(function(f){a.j.listen(f,"click",function(){return BU(a)})})},DU=function(a,b){var c=b.target,d=yU(a,c);d&&(d===a.h||a.h.contains(c)?zU(a,b):CU(a,d))},BU=function(a,b){b=void 0===b?0:b;_ds.Rj(a.m);window.clearTimeout(a.F);var c=a.querySelector("tab[dropdown--open]");if(c){var d=c.querySelector(".devsite-tabs-dropdown");d.setAttribute("dropdown-transition",
"");_ds.Pj(a.m,d,_ds.Av,function(){d.removeAttribute("dropdown-transition");a.removeAttribute("dropdown--open")});a.F=window.setTimeout(function(){c.removeAttribute("dropdown--open");FU(c)},b)}else a.removeAttribute("dropdown--open");AU(a)},CU=function(a,b){AU(a);if(b.hasAttribute("dropdown")){if(_ds.Rj(a.m),window.clearTimeout(a.F),!b.hasAttribute("dropdown--open")){document.body.hasAttribute("touch")&&_ds.Pj(a.m,document.body,"click",function(m){a.contains(m.target)||BU(a)});var c=a.querySelector("tab[dropdown--open]"),
d=b.querySelector(".devsite-tabs-dropdown");if(d){_ds.Uj(d,"left","");var f=_ds.Kg(window||window),g=Array.from(d.querySelectorAll(".devsite-tabs-dropdown-column"));if(!b.hasAttribute("dropdown-full")&&1<g.length){var k=[];g.forEach(function(m){k.push(m.scrollWidth)});var l=Math.max.apply(null,k);l*g.length<f.width?g.forEach(function(m){_ds.Uj(m,"width",l+"px")}):b.setAttribute("dropdown-full","")}g=d.getBoundingClientRect();b.hasAttribute("dropdown-full")?_ds.Uj(d,"left","-"+g.left+"px"):(f=Math.min(g.left,
g.left+g.width-f.width),0<f&&_ds.Uj(d,"left","-"+f+"px"));c?(c.removeAttribute("dropdown--open"),FU(c),c.querySelector(".devsite-tabs-dropdown").removeAttribute("dropdown-transition")):(d.setAttribute("dropdown-transition",""),_ds.Pj(a.m,d,_ds.Av,function(){return d.removeAttribute("dropdown-transition")}));window.requestAnimationFrame(function(){a.setAttribute("dropdown--open","");b.setAttribute("dropdown--open","");FU(b)})}else c&&(c.removeAttribute("dropdown--open"),FU(c))}}else BU(a)},yU=function(a,
b){for(;b&&b!==a;){if("TAB"===b.tagName.toUpperCase())return b;b=b.parentElement}return null},zU=function(a,b){var c;_ds.D(function(d){if(1==d.h)return b.preventDefault(),b.stopPropagation(),document.body.dispatchEvent(new CustomEvent("devsite-close-overflow-tabs")),_ds.v(d,_ds.Ji(),2);if(a.hasAttribute("overflow-menu--open"))return d.return();document.body.hasAttribute("touch")&&(c=function(f){a.contains(f.target)||AU(a);_ds.Qj(a.m,document.body,["devsite-close-overflow-tabs","click"],c)},a.m.listen(document.body,
["devsite-close-overflow-tabs","click"],c));a.C.removeAttribute("hidden");a.setAttribute("overflow-menu--open","");_ds.x(d)})},AU=function(a){a.C.setAttribute("hidden","");a.removeAttribute("overflow-menu--open")},wU=function(a){a.h.setAttribute("hidden","");if(!(3>a.o.length)){var b=GU(a);if(0!==b){var c=a.o.slice(),d=0,f;c.forEach(function(p){p.parentNode!==a.D&&(f?_ds.Xg(p,f):_ds.Yg(a.D,p,0));f=p;d+=GU(p)});if(!(d<=b)){var g=a.L;a.h.removeAttribute("hidden");var k=a.querySelector("[active]");for(k&&
(g+=GU(k));c.length;){var l=c.shift();if(l!==k){var m=GU(l);g+m<=b?g+=m:a.C.appendChild(l)}}}}}},HU=function(a){a.o=Array.from(a.querySelectorAll("tab"));var b=a.querySelector(".devsite-tabs-wrapper");b||(b=a.ownerDocument.createElement("div"),b.classList.add("devsite-tabs-wrapper"),a.appendChild(b),a.o.forEach(function(f){return b.appendChild(f)}));a.D=b;a.appendChild(b);if(!a.hasAttribute("no-overflow")){var c=a.ownerDocument.createElement("tab");c.setAttribute("overflow-tab","");var d=a.ownerDocument.createElement("a");
_ds.Fd(d,"#");d.textContent="\u66f4\u591a\u9078\u9805";d.classList.add("devsite-icon");d.classList.add("devsite-icon-arrow-drop-down");c.appendChild(d);a.h=c;d=a.ownerDocument.createElement("div");d.classList.add("devsite-tabs-overflow-menu");d.setAttribute("scrollbars","");d.setAttribute("hidden","");a.C=d;c.appendChild(d);b.appendChild(c)}},GU=function(a){if(!a)return 0;for(var b=[],c=a;c.parentElement&&0==c.offsetWidth;)b.push(c),c.setAttribute("render-hidden",""),c=c.parentElement;a=_ds.fk(a).width;
b=_ds.t(b);for(c=b.next();!c.done;c=b.next())c.value.removeAttribute("render-hidden");return a},FU=function(a){var b=a.querySelector(".devsite-tabs-dropdown-toggle"),c=a.hasAttribute("dropdown--open"),d=a.querySelector(".devsite-tabs-dropdown");a.querySelector("a").setAttribute("aria-expanded",c);b.setAttribute("aria-expanded",c);d.setAttribute("aria-hidden",!c)},KU=function(a){a.o.forEach(function(b,c){if(b.hasAttribute("generated-tab-menu")&&!document.body.hasAttribute("touch")){var d=Array.from(b.querySelectorAll(".devsite-tabs-dropdown-column")),
f=b.querySelector(".devsite-tabs-dropdown"),g=b.querySelector("a");d.forEach(function(k,l){k.setAttribute("column-id","tab-"+c+"-column-"+l)});d=d.map(function(k){var l=k.querySelector(".devsite-nav-title")||k.querySelector(".devsite-nav-item-title");return{$h:k.getAttribute("column-id"),text:l.textContent}});g&&(g=_ds.Zp(uU,{Kg:g.textContent,Kl:d}),f&&(d=b.querySelector(".devsite-tabs-dropdown-content")))&&(f.insertBefore(g,d),f=b.querySelector(".dropdown-tabbed-menu a"),IU(b),a.j.listen(g,"click",
function(k){k.preventDefault();var l=b.querySelector(".dropdown-tabbed-menu-button");k=k.target;l&&k.tagName&&"a"===k.tagName.toLowerCase()&&!l.contains(k)&&JU(b,k.getAttribute("column-id"))}),f&&JU(b,f.getAttribute("column-id")))}})},JU=function(a,b){var c=Array.from(a.querySelectorAll(".devsite-tabs-dropdown-column"));a=Array.from(a.querySelectorAll(".dropdown-tabbed-menu a"));a.forEach(function(d){return d.removeAttribute("active")});c.forEach(function(d){return d.setAttribute("hidden","")});a=
a.find(function(d){return d.getAttribute("column-id")===b});c=c.find(function(d){return d.getAttribute("column-id")===b});a&&c&&(a.setAttribute("active",""),c.removeAttribute("hidden"))},IU=function(a){var b=a.querySelector(".dropdown-tabbed-menu-button-target");if(!a.querySelector(".dropdown-tabbed-menu-button")&&b){var c=a.querySelector("a");c&&(c=c.textContent,b=b.querySelector(".devsite-nav-item a"),a=a.querySelector(".dropdown-tabbed-menu"),b&&(c=_ds.Zp(vU,{Kg:c,href:b.getAttribute("href"),text:b.textContent}),
a.appendChild(c)))}};_ds.u(xU,_ds.U);xU.prototype.disconnectedCallback=function(){_ds.Rj(this.j);_ds.Rj(this.m)};xU.prototype.connectedCallback=function(){this.G||(HU(this),this.G=!0);this.setAttribute("connected","");this.hasAttribute("no-overflow")||(this.h.setAttribute("collapsed",""),this.L=GU(this.h),this.h.removeAttribute("collapsed"),EU(this),wU(this));KU(this)};xU.prototype.connectedCallback=xU.prototype.connectedCallback;xU.prototype.disconnectedCallback=xU.prototype.disconnectedCallback;try{window.customElements.define("devsite-tabs",xU)}catch(a){console.warn("devsite.app.customElement.DevsiteTabs",a)};})(_ds_www);
