(function(_ds){var window=this;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var NM=function(a,b){KM()&&(b=LM()?"translate3d("+b+"px,0px,0px)":"translate("+b+"px,0px)",_ds.Uj(a,MM(),b))},QM=function(){var a=_ds.U.call(this)||this;a.H=-1;a.h=new _ds.Lj;a.G=new _ds.Lj;a.C=0;a.J=new MutationObserver(function(){return OM(a)});a.N=new _ds.Ij(function(){OM(a);PM(a)},15);a.L=0;a.m=0;a.o=0;a.j=0;a.D=!1;return a},SM=function(a){a.h.listen(a,"devsite-search-toggle",function(b){b=b.Z;_ds.zh(b.target,"devsite-top-logo-row-middle")&&(b.detail.active?a.setAttribute("search-active",
""):a.removeAttribute("search-active"))});a.h.listen(document.body,"devsite-sitemask-hidden",function(){return document.body.removeAttribute("devsite-book-nav--open")});a.h.listen(window,"resize",function(){return RM(a)});a.h.listen(document.body,["devsite-page-loaded","devsite-content-updated"],function(){RM(a)});a.h.listen(a,"click",function(b){b.defaultPrevented||"devsite-hamburger-menu"!=b.target.getAttribute("id")||(b.preventDefault(),b.stopPropagation(),document.body.setAttribute("devsite-book-nav--open",
""),a.dispatchEvent(new CustomEvent("devsite-sitemask-show",{bubbles:!0})))})},RM=function(a){window.requestAnimationFrame(function(){return a.N.qa()})},TM=function(a,b){return(a=a.querySelector(b))?a.getBoundingClientRect().height:0},OM=function(a){a.L=TM(a,".devsite-top-logo-row-wrapper-wrapper");a.m=TM(a,".devsite-collapsible-section");a.o=TM(a,".devsite-doc-set-nav-row");a.setAttribute("top-row--height",a.L);a.setAttribute("bottom-row--height",a.m);a.setAttribute("bottom-tabs--height",a.o);UM(a)},
VM=function(a){if(!a.querySelector(".devsite-search-background")&&(a=a.querySelector(".devsite-top-logo-row-middle"))){var b=document.createElement("div");b.classList.add("devsite-search-background");b.style.opacity=1;a.appendChild(b)}},UM=function(a){var b=a.querySelector(".devsite-collapsible-section");a.j>=a.m&&!a.hasAttribute("bottom-row--hidden")?a.setAttribute("bottom-row--hidden",""):a.j<a.m-a.o&&a.hasAttribute("bottom-row--hidden")&&a.removeAttribute("bottom-row--hidden");b&&a.j!==a.H&&(_ds.Uj(b,
"transform","translate3d(0, -"+a.j+"px, 0)"),PM(a),a.H=a.j)},WM=function(a){var b=a.querySelector(".devsite-top-logo-row-middle"),c=a.querySelector("devsite-search"),d=a.querySelector(".devsite-search-background");if(b&&c&&d){_ds.Rj(a.G);a.C&&window.cancelAnimationFrame(a.C);c.removeAttribute("transition");a.removeAttribute("search-expanded");var f=new _ds.vg(b.offsetWidth,b.offsetHeight);b=new _ds.vg(c.offsetWidth,c.offsetHeight);var g=_ds.lk(c,"margin"),k="rtl"===document.documentElement.getAttribute("dir")?
1:-1,l=(f.width-g.left-g.right)/b.width;f=(f.width-(b.width+g.left+g.right))*k;var m=(g=a.hasAttribute("search-active"))?f:0,p=g?l:1;_ds.Uj(d,{opacity:1,width:b.width+"px",height:b.height+"px"});NM(c,a.hasAttribute("search-active")?0:f);_ds.Pj(a.G,d,_ds.Av,function(){var q=a.querySelector("devsite-search"),r=a.querySelector(".devsite-search-background");r&&(r.style.opacity=0);q&&(q.removeAttribute("transition"),NM(q,0),a.hasAttribute("search-active")?a.setAttribute("search-expanded",""):a.removeAttribute("search-expanded"))});
a.C=window.requestAnimationFrame(function(){c.setAttribute("transition","");if(KM()){var q=LM()?"scale3d("+p+",1,1)":"scale("+p+",1)";_ds.Uj(d,MM(),q)}NM(c,m)})}},XM=function(a,b){var c,d,f,g;_ds.D(function(k){if(1==k.h){if(!a.hasAttribute("billboard"))return k.return();c=a.querySelector("devsite-search");d=a.querySelector("devsite-search input.devsite-search-query");f=a.querySelector(".devsite-header-billboard-search devsite-search");g=f.querySelector("input.devsite-search-query");if(!b)return f.removeAttribute("disabled"),
document.activeElement===d&&g.focus(),c.setAttribute("disabled",""),k.K(0);c.removeAttribute("disabled");return document.activeElement!==g?k.K(3):_ds.v(k,_ds.Ji(),4)}3!=k.h&&d.focus();f.setAttribute("disabled","");_ds.x(k)})},PM=function(a){0===a.m?a.setAttribute("no-lower-row",""):a.removeAttribute("no-lower-row");a.querySelector(".devsite-header-billboard")?a.setAttribute("billboard",""):a.removeAttribute("billboard")},YM=function(a,b){for(var c=0;c<b.attributes.length;++c){var d=b.attributes.item(c);
a.hasAttribute(d.name)||b.removeAttribute(d.name)}for(c=0;c<a.attributes.length;++c)d=a.attributes.item(c),b.setAttribute(d.name,d.value)},ZM=function(a,b,c){b=b.querySelector(c);c=a.querySelector(c);b&&c&&(a.D=!0,_ds.Al(a,c,b))};var KM=_ds.Tb(function(){return!_ds.Mg||0<=_ds.Fc(_ds.Lw,9)}),LM=_ds.Tb(function(){return _ds.Og||_ds.fq||_ds.Wj&&0<=_ds.Fc(_ds.Lw,10)||_ds.Mg&&0<=_ds.Fc(_ds.Lw,10)}),MM=_ds.Tb(function(){return _ds.Mg&&9==_ds.Fe?"-ms-transform":"transform"});_ds.u(QM,_ds.U);QM.prototype.attributeChangedCallback=function(a,b,c){switch(a){case "offset":this.j=parseFloat(this.getAttribute("offset"))||0;UM(this);break;case "search-active":WM(this);break;case "bottom-row--hidden":a=null!==c,b=this.querySelector("devsite-search input.devsite-search-query"),c=this.querySelector(".devsite-header-billboard-search devsite-search input.devsite-search-query"),b&&c&&(a?b.value=c.value:c.value=b.value),XM(this,a)}};
QM.prototype.connectedCallback=function(){SM(this);VM(this);PM(this);OM(this);this.J.observe(this,{childList:!0,subtree:!0});UM(this);var a=_ds.ui();this.F=_ds.ki(_ds.mi(a.href),"authuser")};QM.prototype.disconnectedCallback=function(){_ds.Rj(this.h);this.J.disconnect()};
QM.prototype.updateContent=function(a){this.D=!1;if(a){ZM(this,a,".devsite-header-upper-tabs");ZM(this,a,".devsite-collapsible-section");ZM(this,a,".devsite-product-name-wrapper");ZM(this,a,"devsite-language-selector");var b=a.querySelector("devsite-search"),c=this.querySelector("devsite-search");b&&c&&YM(b,c);c=a.querySelector("devsite-user");b=this.querySelector("devsite-user");c&&b&&(YM(c,b),c=_ds.ui(),c=_ds.ki(_ds.mi(c.href),"authuser"),c!==this.F&&(this.F=c,b.refresh()));_ds.Al(this,this.querySelector("cloudx-additional-tabs"),
a.querySelector("cloudx-additional-tabs"),this.querySelector(".devsite-top-logo-row-middle"));_ds.Al(this,this.querySelector(".devsite-header-link"),a.querySelector(".devsite-header-link"),this.querySelector("devsite-language-selector"))}!this.D&&a&&(_ds.Vg(this),this.appendChild(a));VM(this);RM(this)};_ds.n.Object.defineProperties(QM,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return["offset","search-active","bottom-row--hidden"]}}});QM.prototype.updateContent=QM.prototype.updateContent;
QM.prototype.disconnectedCallback=QM.prototype.disconnectedCallback;QM.prototype.connectedCallback=QM.prototype.connectedCallback;QM.prototype.attributeChangedCallback=QM.prototype.attributeChangedCallback;try{window.customElements.define("devsite-header",QM)}catch(a){console.warn("devsite.app.customElement.DevsiteHeader",a)};})(_ds_www);
