(function(_ds){var window=this;'use strict';var aR=function(){return(0,_ds.X)('<div class="devsite-select"></div>')},bR=function(a){var b=a.Qc,c=a.jg;a='<label id="'+_ds.Z(a.id)+'-label" style="display:none;"'+(b?' aria-label="'+_ds.Z(b)+'"':"")+">";return(0,_ds.X)((c?a+"\u9078\u53d6\u4e00\u500b\u4ee5\u4e0a\u7684\u9078\u9805":a+"\u9078\u53d6\u9078\u9805")+"</label>")},cR=function(a){var b=a.label;a=a.id;return(0,_ds.X)('<button type="button" class="devsite-select-toggle" id="'+_ds.Z(a)+'-button" aria-haspopup="true" aria-labelledby="'+
_ds.Z(a)+"-label "+_ds.Z(a)+'-button" aria-controls="'+_ds.Z(a)+'-popup">'+_ds.Y(b)+"</button>")},dR=function(){return(0,_ds.X)('<span class="devsite-icon devsite-icon-arrow-drop-down devsite-select-toggle-icon" aria-hidden="true"></span>')},eR=function(a){var b=a.options,c=a.id;a=a.jg;a='<ul class="devsite-select-list" id="'+_ds.Z(c)+'-popup" tabindex="-1" role="listbox" scrollbars aria-labelledby="'+_ds.Z(c)+'-button"'+(a?' aria-multiselectable="true"':"")+">";for(var d=b.length,f=0;f<d;f++){var g=
b[f];a+='<li role="option"';for(var k=_ds.Qs(g.attributes),l=k.length,m=0;m<l;m++){var p=k[m];a+=" "+_ds.Ep(p)+'="'+_ds.Z(g.attributes.get(p))+'"'}a+=' id="'+_ds.Z(c)+"-"+_ds.Z(f)+'" class="devsite-select-item" data-index="'+_ds.Z(f)+'"'+(g.defaultSelected?' data-selected aria-selected="true"':' aria-selected="false"')+' aria-label="'+_ds.Z(g.Qc)+'">'+_ds.Y(g.label)+"</li>"}return(0,_ds.X)(a+"</ul>")},fR=function(){var a=_ds.U.call(this)||this;a.m=null;a.H=null;a.D=new _ds.Lj;a.F=new _ds.Lj;a.J=null;
a.L=!1;a.o=!1;a.N="";a.h=null;a.C=null;a.j=null;a.G=null;a.O=new _ds.Jj;return a},gR=function(a){var b=a.querySelector(".kd-select");b&&(b.classList.remove("kd-select"),Array.from(b.classList).forEach(function(c){a.classList.add(c);b.classList.remove(c)}))},lR=function(a){a.j=a.querySelector("select");var b;(b=a.j.id)||(hR++,b="devsite-select-"+hR+Math.random().toString().substr(2));a.j&&(a.j.options.length&&(a.G=a.j.options),a.j.hasAttribute("multiple")&&(a.o=!0,a.classList.add("devsite-select--multiple")));
if(a.G){var c=_ds.Zp(aR),d=a.j.options;d=d[a.j.selectedIndex]||d[0];a.N=a.hasAttribute("label")?a.getAttribute("label"):d.label;d={Qc:a.j.getAttribute("aria-label"),id:b,jg:a.o};d=_ds.Zp(bR,d);c.appendChild(d);a.C=_ds.Zp(cR,{label:a.N,id:b});d=_ds.Zp(dR);c.appendChild(a.C);c.appendChild(d);a.h=_ds.Zp(eR,{options:Array.from(a.G).map(function(f){for(var g=f.defaultSelected,k=iR(f.label,f.defaultSelected),l=f.label,m=new Map,p=_ds.t(jR),q=p.next();!q.done;q=p.next())q=q.value,f.hasAttribute(q)&&m.set(q,
f.getAttribute(q));return{defaultSelected:g,Qc:k,label:l,attributes:m}}),id:b,jg:a.o});c.appendChild(a.h);a.appendChild(c);a.j.hasAttribute("disabled")&&a.querySelector(".devsite-select-toggle").setAttribute("disabled","");kR(a)}a.L=!0},kR=function(a){a.D.listen(a.C,"click",function(b){clearTimeout(a.J);a.dispatchEvent(new CustomEvent("devsite-close-select",{bubbles:!0}));b.preventDefault();b.stopPropagation();a.hasAttribute("menu--open")?mR(a):nR(a)});a.D.listen(a.h,"click",function(b){b.target.classList.contains("devsite-select-item")&&
oR(a,b.target)});a.D.listen(a.h,"focusout",function(){a.J=setTimeout(function(){return mR(a)},200)});a.D.listen(a.j,"change",function(){pR(a,qR(a.querySelectorAll("option")))});a.D.listen(a.h,"keydown",function(b){var c=b.which||b.keyCode;switch(c){case 38:case 40:b.preventDefault();if(a.m){if(b=40===c?_ds.ch(a.m):_ds.dh(a.m))a.m.classList.remove("devsite-focused"),a.h.setAttribute("aria-activedescendant",b.id),b.classList.add("devsite-focused"),a.m=b}else rR(a);a.m.scrollIntoView({block:"nearest"});
break;case 13:case 32:b.preventDefault();oR(a,a.m);break;case 9:case 27:mR(a)}});a.D.listen(a.C,"keydown",function(b){var c=b.which||b.keyCode;if(38===c||40===c)b.preventDefault(),a.hasAttribute("menu--open")||nR(a)})},nR=function(a){a.setAttribute("menu--open","");a.setAttribute("aria-expanded","true");rR(a);a.h.focus();"scrollIntoViewIfNeeded"in a.m&&a.m.scrollIntoViewIfNeeded()},mR=function(a){a.removeAttribute("menu--open");a.removeAttribute("aria-expanded");a.F.listen(document.body,"click",a.H);
a.F.listen(document.body,"devsite-close-select",a.H);a.m&&a.m.classList.remove("devsite-focused")},oR=function(a,b){b&&(sR(a,parseInt(b.dataset.index,10)),a.o||(mR(a),a.C.focus()),a.j.dispatchEvent(new Event("change")))},rR=function(a){if(a.h){var b=Array.from(a.h.children).find(function(c){return c.hasAttribute("data-selected")});a.m=b?b:a.h.children[0];a.h.setAttribute("aria-activedescendant",a.m.id)}},tR=function(a){a.H=function(b){if("devsite-close-select"!==b.type||b.target!==a)a.o&&"devsite-select-item"===
b.target.className||mR(a)};a.h&&(a.F.listen(document.body,"click",a.H),a.F.listen(document.body,"devsite-close-select",a.H))},uR=function(a){if(a.h&&a.C){a.h.style.removeProperty("left");a.h.style.removeProperty("right");var b=a.h.getBoundingClientRect();0<b.x+b.width-_ds.Kj(a.O).width?a.h.style.right="0":a.h.style.left="0"}},qR=function(a){return Array.from(a).reduce(function(b,c,d){c.selected&&b.push(d);return b},[])},sR=function(a,b){var c=a.querySelectorAll("option");if(c&&c.length){if(!a.o)for(var d=
_ds.t(c),f=d.next();!f.done;f=d.next())f.value.removeAttribute("selected");c[b]&&(b=c[b],a.o&&b.hasAttribute("selected")?b.removeAttribute("selected"):b.setAttribute("selected","true"));pR(a,qR(c))}},pR=function(a,b){var c=a.querySelectorAll(".devsite-select-item");Array.from(c).forEach(function(d,f){d=!1;b.includes(f)?(d=!0,c[f].setAttribute("data-selected",""),c[f].setAttribute("aria-selected","true"),a.h.setAttribute("aria-activedescendant",c[f].id)):(c[f].removeAttribute("data-selected"),c[f].setAttribute("aria-selected",
"false"));c[f].setAttribute("aria-label",iR(c[f].textContent,d))});a.o||(a.C.textContent=a.j.options[b[0]].label);uR(a)},iR=function(a,b){return(void 0===b?0:b)?"\u5df2\u9078\u53d6\u300c"+(a+"\u300d"):a},hR=0;var jR=["lang","title","value"];_ds.u(fR,_ds.U);
fR.prototype.attributeChangedCallback=function(a,b,c){var d=this;return _ds.D(function(f){if(1==f.h){if("menu--open"!==a||b===c)return f.K(2);if(!d.hasAttribute("menu--open"))return d.removeAttribute("menu--show"),_ds.Rj(d.F),f.K(2);uR(d);d.removeAttribute("menu-position");if(d.h){var g=d.h.getBoundingClientRect(),k=_ds.Kj(d.O).height,l=parseInt(_ds.Yj(d.h,"maxHeight"),10);d.setAttribute("menu-position",g.top+(d.h.scrollHeight>l?l:d.h.scrollHeight)<k?"below":"above")}tR(d);return _ds.v(f,0,4)}2!=
f.h&&d.setAttribute("menu--show","");"reset"===a&&sR(d,0);_ds.x(f)})};fR.prototype.connectedCallback=function(){this.L||(gR(this),lR(this))};fR.prototype.disconnectedCallback=function(){_ds.Rj(this.F);_ds.Rj(this.D)};_ds.n.Object.defineProperties(fR.prototype,{value:{configurable:!0,enumerable:!0,get:function(){return this.j.value},set:function(a){oR(this,this.h.querySelector('.devsite-select-item[value="'+a+'"]'))}}});
_ds.n.Object.defineProperties(fR,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return["label","menu--open","reset"]}}});fR.prototype.disconnectedCallback=fR.prototype.disconnectedCallback;fR.prototype.connectedCallback=fR.prototype.connectedCallback;fR.prototype.attributeChangedCallback=fR.prototype.attributeChangedCallback;try{window.customElements.define("devsite-select",fR)}catch(a){console.warn("devsite.app.customElement.DevsiteSelect",a)};})(_ds_www);
