(function(_ds){var window=this;'use strict';var lJ=function(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c];if(_ds.mb(d)){var f=a.length||0,g=d.length||0;a.length=f+g;for(var k=0;k<g;k++)a[f+k]=d[k]}else a.push(d)}},mJ=function(){var a=new _ds.ns;lJ(a.L,"data-devsite-credential-type data-modal-dialog-id data-scope data-terminal-prefix data-title data-type".split(" "));return a},nJ=function(){var a=mJ();_ds.fd(["devsite-var"],function(b){this.J.push(b)},a);return a},oJ=function(){var a='<div class="devsite-code-buttons-container" role="group" aria-label="'+
_ds.qp("\u52d5\u4f5c\u6309\u9215");return(0,_ds.X)(a+'"></div>')},pJ=function(a){a=a.label;return(0,_ds.X)('<button type="button" class="gc-analytics-event material-icons devsite-icon-code-dark devsite-toggle-dark" data-category="Site-Wide Custom Events" data-label="Dark Code Toggle" track-type="exampleCode" track-name="darkCodeToggle" aria-label="'+_ds.Z(a)+'" data-title="'+_ds.Z(a)+'"></button>')},qJ=function(a){a=a.label;return(0,_ds.X)('<button type="button" class="gc-analytics-event material-icons devsite-icon-code-light devsite-toggle-light" data-category="Site-Wide Custom Events" data-label="Light Code Toggle" track-type="exampleCode" track-name="lightCodeToggle" aria-label="'+
_ds.Z(a)+'" data-title="'+_ds.Z(a)+'"></button>')},rJ=function(a){var b=a.label;return(0,_ds.X)('<button type="button" class="gc-analytics-event material-icons devsite-icon-copy" data-category="Site-Wide Custom Events" data-label="'+_ds.Z(a.Nl)+'" track-type="exampleCode" track-name="clickToCopy" aria-label="'+_ds.Z(b)+'" data-title="'+_ds.Z(b)+'"></button>')},sJ=function(a){a=a.label;return(0,_ds.X)('<button type="button" class="gc-analytics-event material-icons devsite-icon-code" data-category="jsfiddle" data-label="" track-type="exampleCode" track-name="jsfiddle" aria-label="'+
_ds.Z(a)+'" data-title="'+_ds.Z(a)+'"></button>')},tJ=function(){var a=_ds.U.call(this,["devsite-snackbar"])||this;a.h=null;a.m=null;a.H="";a.C=null;a.j=new _ds.Lj;a.J=!1;a.o=null;a.D=null;a.L=new _ds.Jl;a.N=new _ds.rs(_ds.xs(nJ()));a.F=null;a.G=new _ds.lr;return a},uJ=function(a){Array.from(a.getElementsByClassName("prettyprint")).forEach(function(b){b.classList.remove("prettyprint");var c=(c=b.className.match(/\blang(?:uage)?-([\w.]+)(?!\S)/))?c[1]:void 0;c=window.prettyPrintOne(b.innerHTML,c);
c=_ds.Js(a.N,c);_ds.Dd(b,c);b.getElementsByTagName("strong").length&&b.classList.add("devsite-code-highlight")})},vJ=function(a){var b=a.getElementsByTagName("pre")[0];if(b){if(b.classList.contains("devsite-disable-click-to-copy")||b.hasAttribute("no-copy")||!b.classList.contains("devsite-click-to-copy")&&!b.classList.contains("prettyprint")&&!b.classList.contains("devsite-terminal"))a.setAttribute("no-copy",""),b.classList.remove("devsite-disable-click-to-copy"),b.removeAttribute("no-copy");a.setAttribute("data-copy-event-label",
b.getAttribute("data-copy-event-label")||"");b.classList.remove("devsite-click-to-copy");b=b.getAttribute("data-label");a.H=b?"\u8907\u88fd\u7a0b\u5f0f\u78bc\u7bc4\u4f8b: "+b:"\u8907\u88fd\u7a0b\u5f0f\u78bc\u7bc4\u4f8b"}var c=a.querySelector(".devsite-enable-open-in-jsfiddle,.devsite-jsfiddle-code-sample");c&&(a.setAttribute("js-fiddle",""),c.classList.remove("devsite-enable-open-in-jsfiddle"),c.classList.add("devsite-jsfiddle-code-sample"));a.hasAttribute("js-fiddle")&&c&&["scope","jsfiddle-title",
"jsfiddle-wrap","jsfiddle-label"].forEach(function(d){c.hasAttribute("data-"+d)&&(a.setAttribute(d,c.getAttribute("data-"+d)),c.removeAttribute("data-"+d))})},wJ=function(a){var b,c;return _ds.D(function(d){if(1==d.h){b=Array.from(a.querySelector("pre:not(.devsite-copy-hide)").childNodes);_ds.Vs(document.body,b);if(!a.F)return d.K(0);c=new _ds.Jl;a.m.setAttribute("aria-label","\u5df2\u5c07\u7a0b\u5f0f\u78bc\u7bc4\u4f8b\u8907\u88fd\u5230\u526a\u8cbc\u7c3f");_ds.Pj(a.j,a.F,_ds.Av,function(){c.resolve()});
return _ds.v(d,c.promise,3)}_ds.Pj(a.j,a.F,_ds.Av,function(){a.m.setAttribute("aria-label",a.H)});_ds.x(d)})},xJ=function(a){a.C&&a.j.listen(a.C,"click",function(){return void a.setAttribute("dark-code","")});a.D&&a.j.listen(a.D,"click",function(){return void a.removeAttribute("dark-code")});a.m&&a.j.listen(a.m,"click",function(){return void wJ(a)});a.o&&a.j.listen(a.o,"click",function(){var b={title:a.getAttribute("jsfiddle-title")||"\u7a0b\u5f0f\u78bc\u7bc4\u4f8b",wrap:a.getAttribute("jsfiddle-wrap")||
"b",description:""},c=a.getAttribute("scope");c?_ds.it(c,b):_ds.ht([a],b)})};/*
 Copyright (C) 2006 Google Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
window.PR_SHOULD_USE_CONTINUATION=!0;window.PR_TAB_WIDTH=8;window.PR_normalizedHtml=void 0;window.PR=void 0;window.prettyPrintOne=void 0;window.prettyPrint=void 0;window._pr_isIE6=function(){var a=navigator&&navigator.userAgent&&navigator.userAgent.match(/\bMSIE ([678])\./);a=a?+a[1]:!1;window._pr_isIE6=function(){return a};return a};
(function(){function a(da){return da.replace(w,"&amp;").replace(z,"&lt;").replace(C,"&gt;")}function b(da,ma,Da){switch(da.nodeType){case 1:var Ma=da.tagName.toLowerCase();ma.push("<",Ma);var Qa=da.attributes,fb=Qa.length;if(fb){if(Da){for(var bb=[],Ra=fb;0<=--Ra;)bb[Ra]=Qa[Ra];bb.sort(function(Oa,cb){return Oa.name<cb.name?-1:Oa.name===cb.name?0:1});Qa=bb}for(Ra=0;Ra<fb;++Ra)bb=Qa[Ra],bb.specified&&ma.push(" ",bb.name.toLowerCase(),'="',bb.value.replace(w,"&amp;").replace(z,"&lt;").replace(C,"&gt;").replace(F,
"&quot;"),'"')}ma.push(">");for(Qa=da.firstChild;Qa;Qa=Qa.nextSibling)b(Qa,ma,Da);!da.firstChild&&/^(?:br|link|img)$/.test(Ma)||ma.push("</",Ma,">");break;case 3:case 4:ma.push(a(da.nodeValue))}}function c(da){function ma(qa){if("\\"!==qa.charAt(0))return qa.charCodeAt(0);switch(qa.charAt(1)){case "b":return 8;case "t":return 9;case "n":return 10;case "v":return 11;case "f":return 12;case "r":return 13;case "u":case "x":return parseInt(qa.substring(2),16)||qa.charCodeAt(1);case "0":case "1":case "2":case "3":case "4":case "5":case "6":case "7":return parseInt(qa.substring(1),
8);default:return qa.charCodeAt(1)}}function Da(qa){if(32>qa)return(16>qa?"\\x0":"\\x")+qa.toString(16);qa=String.fromCharCode(qa);if("\\"===qa||"-"===qa||"["===qa||"]"===qa)qa="\\"+qa;return qa}function Ma(qa){var va=qa.substring(1,qa.length-1).match(/\\u[0-9A-Fa-f]{4}|\\x[0-9A-Fa-f]{2}|\\[0-3][0-7]{0,2}|\\[0-7]{1,2}|\\[\s\S]|-|[^-\\]/g);qa=[];for(var H=[],Sa="^"===va[0],xa=Sa?1:0,Pa=va.length;xa<Pa;++xa){var ja=va[xa];switch(ja){case "\\B":case "\\b":case "\\D":case "\\d":case "\\S":case "\\s":case "\\W":case "\\w":qa.push(ja);
continue}ja=ma(ja);if(xa+2<Pa&&"-"===va[xa+1]){var kb=ma(va[xa+2]);xa+=2}else kb=ja;H.push([ja,kb]);65>kb||122<ja||(65>kb||90<ja||H.push([Math.max(65,ja)|32,Math.min(kb,90)|32]),97>kb||122<ja||H.push([Math.max(97,ja)&-33,Math.min(kb,122)&-33]))}H.sort(function(kc,Ze){return kc[0]-Ze[0]||Ze[1]-kc[1]});va=[];ja=[NaN,NaN];for(xa=0;xa<H.length;++xa)Pa=H[xa],Pa[0]<=ja[1]+1?ja[1]=Math.max(ja[1],Pa[1]):va.push(ja=Pa);H=["["];Sa&&H.push("^");H.push.apply(H,qa);for(xa=0;xa<va.length;++xa)Pa=va[xa],H.push(Da(Pa[0])),
Pa[1]>Pa[0]&&(Pa[1]+1>Pa[0]&&H.push("-"),H.push(Da(Pa[1])));H.push("]");return H.join("")}function Qa(qa){for(var va=qa.source.match(/(?:\[(?:[^\x5C\x5D]|\\[\s\S])*\]|\\u[A-Fa-f0-9]{4}|\\x[A-Fa-f0-9]{2}|\\[0-9]+|\\[^ux0-9]|\(\?[:!=]|[\(\)\^]|[^\x5B\x5C\(\)\^]+)/g),H=va.length,Sa=[],xa=0,Pa=0;xa<H;++xa){var ja=va[xa];"("===ja?++Pa:"\\"===ja.charAt(0)&&(ja=+ja.substring(1))&&ja<=Pa&&(Sa[ja]=-1)}for(xa=1;xa<Sa.length;++xa)-1===Sa[xa]&&(Sa[xa]=++fb);for(Pa=xa=0;xa<H;++xa)ja=va[xa],"("===ja?(++Pa,void 0===
Sa[Pa]&&(va[xa]="(?:")):"\\"===ja.charAt(0)&&(ja=+ja.substring(1))&&ja<=Pa&&(va[xa]="\\"+Sa[Pa]);for(Pa=xa=0;xa<H;++xa)"^"===va[xa]&&"^"!==va[xa+1]&&(va[xa]="");if(qa.ignoreCase&&bb)for(xa=0;xa<H;++xa)ja=va[xa],qa=ja.charAt(0),2<=ja.length&&"["===qa?va[xa]=Ma(ja):"\\"!==qa&&(va[xa]=ja.replace(/[a-zA-Z]/g,function(kb){kb=kb.charCodeAt(0);return"["+String.fromCharCode(kb&-33,kb|32)+"]"}));return va.join("")}for(var fb=0,bb=!1,Ra=!1,Oa=0,cb=da.length;Oa<cb;++Oa){var Xa=da[Oa];if(Xa.ignoreCase)Ra=!0;
else if(/[a-z]/i.test(Xa.source.replace(/\\u[0-9a-f]{4}|\\x[0-9a-f]{2}|\\[^ux]/gi,""))){bb=!0;Ra=!1;break}}var Ya=[];Oa=0;for(cb=da.length;Oa<cb;++Oa){Xa=da[Oa];if(Xa.global||Xa.multiline)throw Error(""+Xa);Ya.push("(?:"+Qa(Xa)+")")}return new RegExp(Ya.join("|"),Ra?"gi":"g")}function d(da){var ma=0;return function(Da){for(var Ma=null,Qa=0,fb=0,bb=Da.length;fb<bb;++fb)switch(Da.charAt(fb)){case "\t":Ma||(Ma=[]);Ma.push(Da.substring(Qa,fb));Qa=da-ma%da;for(ma+=Qa;0<=Qa;Qa-=16)Ma.push("                ".substring(0,
Qa));Qa=fb+1;break;case "\n":ma=0;break;default:++ma}if(!Ma)return Da;Ma.push(Da.substring(Qa));return Ma.join("")}}function f(da,ma,Da,Ma){ma&&(da={source:ma,Th:da},Da(da),Ma.push.apply(Ma,da.ni))}function g(da,ma){function Da(bb){for(var Ra=bb.Th,Oa=[Ra,"pln"],cb=0,Xa=bb.source.match(Qa)||[],Ya={},qa=0,va=Xa.length;qa<va;++qa){var H=Xa[qa],Sa=Ya[H],xa=void 0;if("string"===typeof Sa)var Pa=!1;else{var ja=Ma[H.charAt(0)];if(ja)xa=H.match(ja[1]),Sa=ja[0];else{for(Pa=0;Pa<fb;++Pa)if(ja=ma[Pa],xa=H.match(ja[1])){Sa=
ja[0];break}xa||(Sa="pln")}!(Pa=5<=Sa.length&&"lang-"===Sa.substring(0,5))||xa&&"string"===typeof xa[1]||(Pa=!1,Sa="src");Pa||(Ya[H]=Sa)}ja=cb;cb+=H.length;if(Pa){Pa=xa[1];var kb=H.indexOf(Pa),kc=kb+Pa.length;xa[2]&&(kc=H.length-xa[2].length,kb=kc-Pa.length);Sa=Sa.substring(5);f(Ra+ja,H.substring(0,kb),Da,Oa);f(Ra+ja+kb,Pa,p(Sa,Pa),Oa);f(Ra+ja+kc,H.substring(kc),Da,Oa)}else Oa.push(Ra+ja,Sa)}bb.ni=Oa}var Ma={},Qa;(function(){for(var bb=da.concat(ma),Ra=[],Oa={},cb=0,Xa=bb.length;cb<Xa;++cb){var Ya=
bb[cb],qa=Ya[3];if(qa)for(var va=qa.length;0<=--va;)Ma[qa.charAt(va)]=Ya;Ya=Ya[1];qa=""+Ya;Oa.hasOwnProperty(qa)||(Ra.push(Ya),Oa[qa]=null)}Ra.push(/[\0-\uffff]/);Qa=c(Ra)})();var fb=ma.length;return Da}function k(da){var ma=[],Da=[];da.tripleQuotedStrings?ma.push(["str",/^(?:'''(?:[^'\\]|\\[\s\S]|'{1,2}(?=[^']))*(?:'''|$)|"""(?:[^"\\]|\\[\s\S]|"{1,2}(?=[^"]))*(?:"""|$)|'(?:[^\\']|\\[\s\S])*(?:'|$)|"(?:[^\\"]|\\[\s\S])*(?:"|$))/,null,"'\""]):da.multiLineStrings?ma.push(["str",/^(?:'(?:[^\\']|\\[\s\S])*(?:'|$)|"(?:[^\\"]|\\[\s\S])*(?:"|$)|`(?:[^\\`]|\\[\s\S])*(?:`|$))/,
null,"'\"`"]):ma.push(["str",/^(?:'(?:[^\\'\r\n]|\\.)*(?:'|$)|"(?:[^\\"\r\n]|\\.)*(?:"|$))/,null,"\"'"]);da.verbatimStrings&&Da.push(["str",/^@"(?:[^"]|"")*(?:"|$)/,null]);var Ma=da.hashComments;Ma&&(da.cStyleComments?(1<Ma?ma.push(["com",/^#(?:##(?:[^#]|#(?!##))*(?:###|$)|.*)/,null,"#"]):ma.push(["com",/^#(?:(?:define|elif|else|endif|error|ifdef|include|ifndef|line|pragma|undef|warning)\b|[^\r\n]*)/,null,"#"]),Da.push(["str",/^<(?:(?:(?:\.\.\/)*|\/?)(?:[\w-]+(?:\/[\w-]+)+)?[\w-]+\.h|[a-z]\w*)>/,
null])):ma.push(["com",/^#[^\r\n]*/,null,"#"]));da.cStyleComments&&(Da.push(["com",/^\/\/[^\r\n]*/,null]),Da.push(["com",/^\/\*[\s\S]*?(?:\*\/|$)/,null]));da.regexLiterals&&Da.push(["lang-regex",new RegExp("^"+r+"(/(?=[^/*])(?:[^/\\x5B\\x5C]|\\x5C[\\s\\S]|\\x5B(?:[^\\x5C\\x5D]|\\x5C[\\s\\S])*(?:\\x5D|$))+/)")]);da=da.keywords.replace(/^\s+|\s+$/g,"");da.length&&Da.push(["kwd",new RegExp("^(?:"+da.replace(/\s+/g,"|")+")\\b"),null]);ma.push(["pln",/^\s+/,null," \r\n\t\u00a0"]);Da.push(["lit",/^@[a-z_$][a-z_$@0-9]*/i,
null],["typ",/^@?[A-Z]+[a-z][A-Za-z_$@0-9]*/,null],["pln",/^[a-z_$][a-z_$@0-9]*/i,null],["lit",/^(?:0x[a-f0-9]+|(?:\d(?:_\d+)*\d*(?:\.\d*)?|\.\d\+)(?:e[+\-]?\d+)?)[a-z]*/i,null,"0123456789"],["pun",/^.[^\s\w\.$@'"`\/#]*/,null]);return g(ma,Da)}function l(da){function ma($e){if($e>Oa){cb&&cb!==Xa&&(Ra.push("</span>"),cb=null);!cb&&Xa&&(cb=Xa,Ra.push('<span class="',cb,'">'));var zo=a(va(Da.substring(Oa,$e))).replace(ja?Sa:H,"$1&#160;");ja=Pa.test(zo);Ra.push(zo.replace(xa,Ao));Oa=$e}}var Da=da.source,
Ma=da.mm,Qa=da.ni,fb=da.nj,bb=da.pk,Ra=[],Oa=0,cb=null,Xa=null,Ya=0,qa=0,va=d(window.PR_TAB_WIDTH),H=/([\r\n ]) /g,Sa=/(^| ) /gm,xa=/\r\n?|\n/g,Pa=/[ \r\n]$/,ja=!0,kb=window._pr_isIE6();bb=kb?bb&&"PRE"===bb.tagName?6===kb?"&#160;\r\n":7===kb?"&#160;<br />\r":8===kb?"&#160;<br />":"&#160;\r":"&#160;<br />":"<br />";if(fb){var kc=[];for(kb=0;10>kb;++kb)kc[kb]=bb+'</li><li class="L'+kb+'">';var Ze="number"===typeof fb?fb-1:0;Ra.push('<ol class="linenums"><li class="L',Ze%10,'"');Ze&&Ra.push(' value="',
Ze+1,'"');Ra.push(">");var Ao=function(){var $e=kc[++Ze%10];return cb?"</span>"+$e+'<span class="'+cb+'">':$e}}else Ao=bb;for(;;)if(Ya<Ma.length&&(qa<Qa.length?Ma[Ya]<=Qa[qa]:1))ma(Ma[Ya]),cb&&(Ra.push("</span>"),cb=null),Ra.push(Ma[Ya+1]),Ya+=2;else if(qa<Qa.length)ma(Qa[qa]),Xa=Qa[qa+1],qa+=2;else break;ma(Da.length);cb&&Ra.push("</span>");fb&&Ra.push("</li></ol>");da.qg=Ra.join("")}function m(da,ma){for(var Da=ma.length;0<=--Da;){var Ma=ma[Da];gb.hasOwnProperty(Ma)?"console"in window&&console.warn("cannot override language handler %s",
Ma):gb[Ma]=da}}function p(da,ma){da&&gb.hasOwnProperty(da)||(da=/^\s*</.test(ma)?"default-markup":"default-code");return gb[da]}function q(da){var ma=da.nk,Da=da.Xi;da.qg=ma;try{var Ma=ma.match(ab);ma=[];var Qa=0,fb=[];if(Ma)for(var bb=0,Ra=Ma.length;bb<Ra;++bb){var Oa=Ma[bb];if(1<Oa.length&&"<"===Oa.charAt(0)){if(!Va.test(Oa))if(sb.test(Oa))ma.push(Oa.substring(9,Oa.length-3)),Qa+=Oa.length-12;else if(tb.test(Oa))ma.push("\n"),++Qa;else if(0<=Oa.indexOf("nocode")&&Oa.replace(/\s(\w+)\s*=\s*(?:"([^"]*)"|'([^']*)'|(\S+))/g,
' $1="$2$3$4"').match(/[cC][lL][aA][sS][sS]="[^"]*\bnocode\b/)){var cb=Oa.match(Sb)[2],Xa=1;var Ya=bb+1;a:for(;Ya<Ra;++Ya){var qa=Ma[Ya].match(Sb);if(qa&&qa[2]===cb)if("/"===qa[1]){if(0===--Xa)break a}else++Xa}Ya<Ra?(fb.push(Qa,Ma.slice(bb,Ya+1).join("")),bb=Ya):fb.push(Qa,Oa)}else fb.push(Qa,Oa)}else{Xa=Oa;var va=Xa.indexOf("&");if(0>va)var H=Xa;else{for(--va;0<=(va=Xa.indexOf("&#",va+1));){var Sa=Xa.indexOf(";",va);if(0<=Sa){var xa=Xa.substring(va+3,Sa),Pa=10;xa&&"x"===xa.charAt(0)&&(xa=xa.substring(1),
Pa=16);var ja=parseInt(xa,Pa);isNaN(ja)||(Xa=Xa.substring(0,va)+String.fromCharCode(ja)+Xa.substring(Sa+1))}}H=Xa.replace(M,"<").replace(aa,">").replace(S,"'").replace(na,'"').replace(Ja," ").replace(ka,"&")}ma.push(H);Qa+=H.length}}var kb=ma.join("");da.source=kb;da.Th=0;da.mm=fb;p(Da,kb)(da);l(da)}catch(kc){"console"in window&&console.log(kc&&kc.stack?kc.stack:kc)}}var r=function(){for(var da="! != !== # % %= & && &&= &= ( * *= += , -= -> / /= : :: ; < << <<= <= = == === > >= >> >>= >>> >>>= ? @ [ ^ ^= ^^ ^^= { | |= || ||= ~ break case continue delete do else finally instanceof return throw try typeof".split(" "),
ma="(?:^^|[+-]",Da=0;Da<da.length;++Da)ma+="|"+da[Da].replace(/([^=<>:&a-z])/g,"\\$1");return ma+")\\s*"}(),w=/&/g,z=/</g,C=/>/g,F=/"/g,M=/&lt;/g,aa=/&gt;/g,S=/&apos;/g,na=/&quot;/g,ka=/&amp;/g,Ja=/&nbsp;/g,$a=/[\r\n]/g,ra=null,ab=/[^<]+|\x3c!--[\s\S]*?--\x3e|<!\[CDATA\[[\s\S]*?\]\]>|<\/?[a-zA-Z](?:[^>"']|'[^']*'|"[^"]*")*>|</g,Va=/^\x3c!--/,sb=/^<!\[CDATA\[/,tb=/^<br\b/i,Sb=/^<(\/?)([a-zA-Z][a-zA-Z0-9]*)/,nc=k({keywords:"break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof alignof align_union asm axiom bool concept concept_map const_cast constexpr decltype dynamic_cast explicit export friend inline late_check mutable namespace nullptr reinterpret_cast static_assert static_cast template typeid typename using virtual wchar_t where break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof abstract boolean byte extends final finally implements import instanceof null native package strictfp super synchronized throws transient as base by checked decimal delegate descending dynamic event fixed foreach from group implicit in interface internal into is lock object out override orderby params partial readonly ref sbyte sealed stackalloc string select uint ulong unchecked unsafe ushort var break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof debugger eval export function get null set undefined var with Infinity NaN caller delete die do dump elsif eval exit foreach for goto if import last local my next no our print package redo require sub undef unless until use wantarray while BEGIN END break continue do else for if return while and as assert class def del elif except exec finally from global import in is lambda nonlocal not or pass print raise try with yield False True None break continue do else for if return while alias and begin case class def defined elsif end ensure false in module next nil not or redo rescue retry self super then true undef unless until when yield BEGIN END break continue do else for if return while case done elif esac eval fi function in local set then until ",
hashComments:!0,cStyleComments:!0,multiLineStrings:!0,regexLiterals:!0}),gb={};m(nc,["default-code"]);m(g([],[["pln",/^[^<?]+/],["dec",/^<!\w[^>]*(?:>|$)/],["com",/^\x3c!--[\s\S]*?(?:-\->|$)/],["lang-",/^<\?([\s\S]+?)(?:\?>|$)/],["lang-",/^<%([\s\S]+?)(?:%>|$)/],["pun",/^(?:<[%?]|[%?]>)/],["lang-",/^<xmp\b[^>]*>([\s\S]+?)<\/xmp\b[^>]*>/i],["lang-js",/^<script\b[^>]*>([\s\S]*?)(<\/script\b[^>]*>)/i],["lang-css",/^<style\b[^>]*>([\s\S]*?)(<\/style\b[^>]*>)/i],["lang-in.tag",/^(<\/?[a-z][^<>]*>)/i]]),
"default-markup htm html mxml xhtml xml xsl".split(" "));m(g([["pln",/^[\s]+/,null," \t\r\n"],["atv",/^(?:"[^"]*"?|'[^']*'?)/,null,"\"'"]],[["tag",/^^<\/?[a-z](?:[\w.:-]*\w)?|\/?>$/i],["atn",/^(?!style[\s=]|on)[a-z](?:[\w:-]*\w)?/i],["lang-uq.val",/^=\s*([^>'"\s]*(?:[^>'"\s\/]|\/(?=\s)))/],["pun",/^[=<>\/]+/],["lang-js",/^on\w+\s*=\s*"([^"]+)"/i],["lang-js",/^on\w+\s*=\s*'([^']+)'/i],["lang-js",/^on\w+\s*=\s*([^"'>\s]+)/i],["lang-css",/^style\s*=\s*"([^"]+)"/i],["lang-css",/^style\s*=\s*'([^']+)'/i],
["lang-css",/^style\s*=\s*([^"'>\s]+)/i]]),["in.tag"]);m(g([],[["atv",/^[\s\S]+/]]),["uq.val"]);m(k({keywords:"break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof alignof align_union asm axiom bool concept concept_map const_cast constexpr decltype dynamic_cast explicit export friend inline late_check mutable namespace nullptr reinterpret_cast static_assert static_cast template typeid typename using virtual wchar_t where ",
hashComments:!0,cStyleComments:!0}),"c cc cpp cxx cyc m".split(" "));m(k({keywords:"null true false"}),["json"]);m(k({keywords:"break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof abstract boolean byte extends final finally implements import instanceof null native package strictfp super synchronized throws transient as base by checked decimal delegate descending dynamic event fixed foreach from group implicit in interface internal into is lock object out override orderby params partial readonly ref sbyte sealed stackalloc string select uint ulong unchecked unsafe ushort var ",
hashComments:!0,cStyleComments:!0,verbatimStrings:!0}),["cs"]);m(k({keywords:"break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof abstract boolean byte extends final finally implements import instanceof null native package strictfp super synchronized throws transient ",
cStyleComments:!0}),["java"]);m(k({keywords:"break continue do else for if return while case done elif esac eval fi function in local set then until ",hashComments:!0,multiLineStrings:!0}),["bsh","csh","sh"]);m(k({keywords:"break continue do else for if return while and as assert class def del elif except exec finally from global import in is lambda nonlocal not or pass print raise try with yield False True None ",hashComments:!0,multiLineStrings:!0,tripleQuotedStrings:!0}),["cv","py"]);m(k({keywords:"caller delete die do dump elsif eval exit foreach for goto if import last local my next no our print package redo require sub undef unless until use wantarray while BEGIN END ",
hashComments:!0,multiLineStrings:!0,regexLiterals:!0}),["perl","pl","pm"]);m(k({keywords:"break continue do else for if return while alias and begin case class def defined elsif end ensure false in module next nil not or redo rescue retry self super then true undef unless until when yield BEGIN END ",hashComments:!0,multiLineStrings:!0,regexLiterals:!0}),["rb"]);m(k({keywords:"break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof debugger eval export function get null set undefined var with Infinity NaN ",
cStyleComments:!0,regexLiterals:!0}),["js"]);m(k({keywords:"all and by catch class else extends false finally for if in is isnt loop new no not null of off on or return super then true try unless until when while yes ",hashComments:3,cStyleComments:!0,multilineStrings:!0,tripleQuotedStrings:!0,regexLiterals:!0}),["coffee"]);m(g([],[["str",/^[\s\S]+/]]),["regex"]);window.PR_normalizedHtml=b;window.prettyPrintOne=function(da,ma,Da){da={nk:da,Xi:ma,nj:Da};q(da);return da.qg};window.prettyPrint=function(da){function ma(){for(var Xa=
window.PR_SHOULD_USE_CONTINUATION?Ra.now()+250:Infinity;Oa<Ma.length&&Ra.now()<Xa;Oa++){var Ya=Ma[Oa];if(Ya.className&&0<=Ya.className.indexOf("prettyprint")){var qa=Ya.className.match(/\blang-(\w+)\b/);qa&&(qa=qa[1]);for(var va=!1,H=Ya.parentNode;H;H=H.parentNode)if(("pre"===H.tagName||"code"===H.tagName||"xmp"===H.tagName)&&H.className&&0<=H.className.indexOf("prettyprint")){va=!0;break}if(!va){H=Ya;null===ra&&(va=document.createElement("PRE"),va.appendChild(document.createTextNode('<!DOCTYPE foo PUBLIC "foo bar">\n<foo />')),
ra=!/</.test(va.innerHTML));if(ra)if(va=H.innerHTML,"XMP"===H.tagName)va=a(va);else{if("PRE"!==H.tagName&&$a.test(va)){var Sa="";H.currentStyle?Sa=H.currentStyle.whiteSpace:window.getComputedStyle&&(Sa=window.getComputedStyle(H,null).whiteSpace);H=!Sa||"pre"===Sa}else H=!0;H||(va=va.replace(/(<br\s*\/?>)[\r\n]+/g,"$1").replace(/(?:[\r\n]+[ \t]*)+/g," "))}else{va=[];for(H=H.firstChild;H;H=H.nextSibling)b(H,va);va=va.join("")}va=va.replace(/(?:\r\n?|\n)$/,"");H=Ya.className.match(/\blinenums\b(?::(\d+))?/);
cb={nk:va,Xi:qa,pk:Ya,nj:H?H[1]&&H[1].length?+H[1]:!0:!1};q(cb);if(Ya=cb.qg)if(qa=cb.pk,"XMP"===qa.tagName){va=document.createElement("PRE");for(H=0;H<qa.attributes.length;++H)Sa=qa.attributes[H],Sa.specified&&("class"===Sa.name.toLowerCase()?va.className=Sa.value:va.setAttribute(Sa.name,Sa.value));va.innerHTML=Ya;qa.parentNode.replaceChild(va,qa)}else qa.innerHTML=Ya}}}Oa<Ma.length?setTimeout(ma,250):da&&da()}for(var Da=[document.getElementsByTagName("pre"),document.getElementsByTagName("code"),
document.getElementsByTagName("xmp")],Ma=[],Qa=0;Qa<Da.length;++Qa)for(var fb=0,bb=Da[Qa].length;fb<bb;++fb)Ma.push(Da[Qa][fb]);Da=null;var Ra=Date;Ra.now||(Ra={now:function(){return(new Date).getTime()}});var Oa=0,cb;ma()};window.PR={combinePrefixPatterns:c,createSimpleLexer:g,registerLangHandler:m,sourceDecorator:k,PR_ATTRIB_NAME:"atn",PR_ATTRIB_VALUE:"atv",PR_COMMENT:"com",PR_DECLARATION:"dec",PR_KEYWORD:"kwd",PR_LITERAL:"lit",PR_NOCODE:"nocode",PR_PLAIN:"pln",PR_PUNCTUATION:"pun",PR_SOURCE:"src",
PR_STRING:"str",PR_TAG:"tag",PR_TYPE:"typ"}})();/*
 Copyright (C) 2009 Onno Hommes.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_COMMENT,/^#[^\r\n]*/,null,"#"],[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[PR.PR_STRING,/^"(?:[^"\\]|\\[\s\S])*(?:"|$)/,null,'"']],[[PR.PR_KEYWORD,/^(?:ADS|AD|AUG|BZF|BZMF|CAE|CAF|CA|CCS|COM|CS|DAS|DCA|DCOM|DCS|DDOUBL|DIM|DOUBLE|DTCB|DTCF|DV|DXCH|EDRUPT|EXTEND|INCR|INDEX|NDX|INHINT|LXCH|MASK|MSK|MP|MSU|NOOP|OVSK|QXCH|RAND|READ|RELINT|RESUME|RETURN|ROR|RXOR|SQUARE|SU|TCR|TCAA|OVSK|TCF|TC|TS|WAND|WOR|WRITE|XCH|XLQ|XXALQ|ZL|ZQ|ADD|ADZ|SUB|SUZ|MPY|MPR|MPZ|DVP|COM|ABS|CLA|CLZ|LDQ|STO|STQ|ALS|LLS|LRS|TRA|TSQ|TMI|TOV|AXT|TIX|DLY|INP|OUT)\s/,
null],[PR.PR_TYPE,/^(?:-?GENADR|=MINUS|2BCADR|VN|BOF|MM|-?2CADR|-?[1-6]DNADR|ADRES|BBCON|[SE]?BANK=?|BLOCK|BNKSUM|E?CADR|COUNT\*?|2?DEC\*?|-?DNCHAN|-?DNPTR|EQUALS|ERASE|MEMORY|2?OCT|REMADR|SETLOC|SUBRO|ORG|BSS|BES|SYN|EQU|DEFINE|END)\s/,null],[PR.PR_LITERAL,/^'(?:-*(?:\w|\\[\x21-\x7e])(?:[\w-]*|\\[\x21-\x7e])[=!?]?)?/],[PR.PR_PLAIN,/^-*(?:[!-z_]|\\[\x21-\x7e])(?:[\w-]*|\\[\x21-\x7e])[=!?]?/i],[PR.PR_PUNCTUATION,/^[^\w\t\n\r \xA0()"\\';]+/]]),["apollo","agc","aea"]);/*
 Copyright (C) 2011 Google Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
PR.registerLangHandler(PR.createSimpleLexer([["opn",/^[\(\{\[]+/,null,"([{"],["clo",/^[\)\}\]]+/,null,")]}"],[PR.PR_COMMENT,/^;[^\r\n]*/,null,";"],[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[PR.PR_STRING,/^"(?:[^"\\]|\\[\s\S])*(?:"|$)/,null,'"']],[[PR.PR_KEYWORD,/^(?:def|if|do|let|quote|var|fn|loop|recur|throw|try|monitor-enter|monitor-exit|defmacro|defn|defn-|macroexpand|macroexpand-1|for|doseq|dosync|dotimes|and|or|when|not|assert|doto|proxy|defstruct|first|rest|cons|defprotocol|deftype|defrecord|reify|defmulti|defmethod|meta|with-meta|ns|in-ns|create-ns|import|intern|refer|alias|namespace|resolve|ref|deref|refset|new|set!|memfn|to-array|into-array|aset|gen-class|reduce|map|filter|find|nil?|empty?|hash-map|hash-set|vec|vector|seq|flatten|reverse|assoc|dissoc|list|list?|disj|get|union|difference|intersection|extend|extend-type|extend-protocol|prn)\b/,
null],[PR.PR_TYPE,/^:[0-9a-zA-Z\-]+/]]),["clj"]);/*
 Copyright (C) 2009 Google Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[ \t\r\n\f]+/,null," \t\r\n\f"]],[[PR.PR_STRING,/^"(?:[^\n\r\f\\"]|\\(?:\r\n?|\n|\f)|\\[\s\S])*"/,null],[PR.PR_STRING,/^'(?:[^\n\r\f\\']|\\(?:\r\n?|\n|\f)|\\[\s\S])*'/,null],["lang-css-str",/^url\(([^\)"']*)\)/i],[PR.PR_KEYWORD,/^(?:url|rgb|!important|@import|@page|@media|@charset|inherit)(?=[^\-\w]|$)/i,null],["lang-css-kw",/^(-?(?:[_a-z]|(?:\\[0-9a-f]+ ?))(?:[_a-z0-9\-]|\\(?:\\[0-9a-f]+ ?))*)\s*:/i],[PR.PR_COMMENT,/^\/\*[^*]*\*+(?:[^\/*][^*]*\*+)*\//],
[PR.PR_COMMENT,/^(?:\x3c!--|--\x3e)/],[PR.PR_LITERAL,/^(?:\d+|\d*\.\d+)(?:%|[a-z]+)?/i],[PR.PR_LITERAL,/^#(?:[0-9a-f]{3}){1,2}/i],[PR.PR_PLAIN,/^-?(?:[_a-z]|(?:\\[\da-f]+ ?))(?:[_a-z\d\-]|\\(?:\\[\da-f]+ ?))*/i],[PR.PR_PUNCTUATION,/^[^\s\w'"]+/]]),["css"]);PR.registerLangHandler(PR.createSimpleLexer([],[[PR.PR_KEYWORD,/^-?(?:[_a-z]|(?:\\[\da-f]+ ?))(?:[_a-z\d\-]|\\(?:\\[\da-f]+ ?))*/i]]),["css-kw"]);PR.registerLangHandler(PR.createSimpleLexer([],[[PR.PR_STRING,/^[^\)"']+/]]),["css-str"]);/*
 Copyright (C) 2010 Google Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[PR.PR_PLAIN,/^(?:"(?:[^"\\]|\\[\s\S])*(?:"|$)|'(?:[^'\\]|\\[\s\S])+(?:'|$))/,null,"\"'"]],[[PR.PR_COMMENT,/^(?:\/\/[^\r\n]*|\/\*[\s\S]*?\*\/)/],[PR.PR_PLAIN,/^(?:[^\/"']|\/(?![\/\*]))+/i]]),["go"]);PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t\n\x0B\x0C\r ]+/,null,"\t\n\x0B\f\r "],[PR.PR_STRING,/^"(?:[^"\\\n\x0C\r]|\\[\s\S])*(?:"|$)/,null,'"'],[PR.PR_STRING,/^'(?:[^'\\\n\x0C\r]|\\[^&])'?/,null,"'"],[PR.PR_LITERAL,/^(?:0o[0-7]+|0x[\da-f]+|\d+(?:\.\d+)?(?:e[+\-]?\d+)?)/i,null,"0123456789"]],[[PR.PR_COMMENT,/^(?:(?:--+(?:[^\r\n\x0C]*)?)|(?:\{-(?:[^-]|-+[^-\}])*-\}))/],[PR.PR_KEYWORD,/^(?:case|class|data|default|deriving|do|else|if|import|in|infix|infixl|infixr|instance|let|module|newtype|of|then|type|where|_)(?=[^a-zA-Z0-9']|$)/,
null],[PR.PR_PLAIN,/^(?:[A-Z][\w']*\.)*[a-zA-Z][\w']*/],[PR.PR_PUNCTUATION,/^[^\t\n\x0B\x0C\r a-zA-Z0-9'"]+/]]),["hs"]);/*

 Copyright (C) 2017 Micha? B?czkowski

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[PR.PR_PUNCTUATION,/^[.!%&()*+,\-;<=>?\[\\\]^{|}:]+/,null,".!%&()*+,-;<=>?[\\]^{|}:"]],[[PR.PR_KEYWORD,/^\b(package|public|protected|private|open|abstract|constructor|final|override|import|for|while|as|typealias|get|set|((data|enum|annotation|sealed) )?class|this|super|val|var|fun|is|in|throw|return|break|continue|(companion )?object|if|try|else|do|when|init|interface|typeof|suspend)\b/],[PR.PR_LITERAL,
/^(?:true|false|null)\b/],[PR.PR_LITERAL,/^(0[xX][0-9a-fA-F_]+L?|0[bB][0-1]+L?|[0-9_.]+([eE]-?[0-9]+)?[fFL]?)/],[PR.PR_TYPE,/^(\b[A-Z]+[a-z][a-zA-Z0-9_$@]*|`.*`)/,null],[PR.PR_COMMENT,/^\/\/.*/],[PR.PR_COMMENT,/^\/\*[\s\S]*?(?:\*\/|$)/],[PR.PR_STRING,/'.'/],[PR.PR_STRING,/^"([^"\\]|\\[\s\S])*"/],[PR.PR_STRING,/^"{3}[\s\S]*?[^\\]"{3}/],[PR.PR_LITERAL,/^@([a-zA-Z0-9_$@]*|`.*`)/],[PR.PR_LITERAL,/^[a-zA-Z0-9_]+@/]]),["kotlin"]);/*
 Copyright (C) 2008 Google Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
PR.registerLangHandler(PR.createSimpleLexer([["opn",/^\(+/,null,"("],["clo",/^\)+/,null,")"],[PR.PR_COMMENT,/^;[^\r\n]*/,null,";"],[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[PR.PR_STRING,/^"(?:[^"\\]|\\[\s\S])*(?:"|$)/,null,'"']],[[PR.PR_KEYWORD,/^(?:block|c[ad]+r|catch|con[ds]|def(?:ine|un)|do|eq|eql|equal|equalp|eval-when|flet|format|go|if|labels|lambda|let|load-time-value|locally|macrolet|multiple-value-call|nil|progn|progv|quote|require|return-from|setq|symbol-macrolet|t|tagbody|the|throw|unwind)\b/,
null],[PR.PR_LITERAL,/^[+\-]?(?:[0#]x[0-9a-f]+|\d+\/\d+|(?:\.\d+|\d+(?:\.\d*)?)(?:[ed][+\-]?\d+)?)/i],[PR.PR_LITERAL,/^'(?:-*(?:\w|\\[\x21-\x7e])(?:[\w-]*|\\[\x21-\x7e])[=!?]?)?/],[PR.PR_PLAIN,/^-*(?:[a-z_]|\\[\x21-\x7e])(?:[\w-]*|\\[\x21-\x7e])[=!?]?/i],[PR.PR_PUNCTUATION,/^[^\w\t\n\r \xA0()"\\';]+/]]),["cl","el","lisp","scm"]);PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[PR.PR_STRING,/^(?:"(?:[^"\\]|\\[\s\S])*(?:"|$)|'(?:[^'\\]|\\[\s\S])*(?:'|$))/,null,"\"'"]],[[PR.PR_COMMENT,/^--(?:\[(=*)\[[\s\S]*?(?:\]\1\]|$)|[^\r\n]*)/],[PR.PR_STRING,/^\[(=*)\[[\s\S]*?(?:\]\1\]|$)/],[PR.PR_KEYWORD,/^(?:and|break|do|else|elseif|end|false|for|function|if|in|local|nil|not|or|repeat|return|then|true|until|while)\b/,null],[PR.PR_LITERAL,/^[+-]?(?:0x[\da-f]+|(?:(?:\.\d+|\d+(?:\.\d*)?)(?:e[+\-]?\d+)?))/i],
[PR.PR_PLAIN,/^[a-z_]\w*/i],[PR.PR_PUNCTUATION,/^[^\w\t\n\r \xA0][^\w\t\n\r \xA0"'\-\+=]*/]]),["lua"]);PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[PR.PR_COMMENT,/^#(?:if[\t\n\r \xA0]+(?:[a-z_$][\w']*|``[^\r\n\t`]*(?:``|$))|else|endif|light)/i,null,"#"],[PR.PR_STRING,/^(?:"(?:[^"\\]|\\[\s\S])*(?:"|$)|'(?:[^'\\]|\\[\s\S])(?:'|$))/,null,"\"'"]],[[PR.PR_COMMENT,/^(?:\/\/[^\r\n]*|\(\*[\s\S]*?\*\))/],[PR.PR_KEYWORD,/^(?:abstract|and|as|assert|begin|class|default|delegate|do|done|downcast|downto|elif|else|end|exception|extern|false|finally|for|fun|function|if|in|inherit|inline|interface|internal|lazy|let|match|member|module|mutable|namespace|new|null|of|open|or|override|private|public|rec|return|static|struct|then|to|true|try|type|upcast|use|val|void|when|while|with|yield|asr|land|lor|lsl|lsr|lxor|mod|sig|atomic|break|checked|component|const|constraint|constructor|continue|eager|event|external|fixed|functor|global|include|method|mixin|object|parallel|process|protected|pure|sealed|trait|virtual|volatile)\b/],
[PR.PR_LITERAL,/^[+\-]?(?:0x[\da-f]+|(?:(?:\.\d+|\d+(?:\.\d*)?)(?:e[+\-]?\d+)?))/i],[PR.PR_PLAIN,/^(?:[a-z_][\w']*[!?#]?|``[^\r\n\t`]*(?:``|$))/i],[PR.PR_PUNCTUATION,/^[^\t\n\r \xA0"'\w]+/]]),["fs","ml"]);PR.registerLangHandler(PR.sourceDecorator({keywords:"bool bytes default double enum extend extensions false fixed32 fixed64 float group import int32 int64 max message option optional package repeated required returns rpc service sfixed32 sfixed64 sint32 sint64 string syntax to true uint32 uint64",cStyleComments:!0}),["proto"]);PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[PR.PR_STRING,/^(?:"(?:(?:""(?:""?(?!")|[^\\"]|\\.)*"{0,3})|(?:[^"\r\n\\]|\\.)*"?))/,null,'"'],[PR.PR_LITERAL,/^`(?:[^\r\n\\`]|\\.)*`?/,null,"`"],[PR.PR_PUNCTUATION,/^[!#%&()*+,\-:;<=>?@\[\\\]^{|}~]+/,null,"!#%&()*+,-:;<=>?@[\\]^{|}~"]],[[PR.PR_STRING,/^'(?:[^\r\n\\']|\\(?:'|[^\r\n']+))'/],[PR.PR_LITERAL,/^'[a-zA-Z_$][\w$]*(?!['$\w])/],[PR.PR_KEYWORD,/^(?:abstract|case|catch|class|def|do|else|extends|final|finally|for|forSome|if|implicit|import|lazy|match|new|object|override|package|private|protected|requires|return|sealed|super|throw|trait|try|type|val|var|while|with|yield)\b/],
[PR.PR_LITERAL,/^(?:true|false|null|this)\b/],[PR.PR_LITERAL,/^(?:(?:0(?:[0-7]+|X[0-9A-F]+))L?|(?:(?:0|[1-9][0-9]*)(?:(?:\.[0-9]+)?(?:E[+\-]?[0-9]+)?F?|L?))|\\.[0-9]+(?:E[+\-]?[0-9]+)?F?)/i],[PR.PR_TYPE,/^[$_]*[A-Z][_$A-Z0-9]*[a-z][\w$]*/],[PR.PR_PLAIN,/^[$a-zA-Z_][\w$]*/],[PR.PR_COMMENT,/^\/(?:\/.*|\*(?:\/|\**[^*/])*(?:\*+\/?)?)/],[PR.PR_PUNCTUATION,/^(?:\.+|\/)/]]),["scala"]);PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[PR.PR_STRING,/^(?:"(?:[^"\\]|\\.)*"|'(?:[^'\\]|\\.)*')/,null,"\"'"]],[[PR.PR_COMMENT,/^(?:--[^\r\n]*|\/\*[\s\S]*?(?:\*\/|$))/],[PR.PR_KEYWORD,/^(?:ADD|ALL|ALTER|AND|ANY|AS|ASC|AUTHORIZATION|BACKUP|BEGIN|BETWEEN|BREAK|BROWSE|BULK|BY|CASCADE|CASE|CHECK|CHECKPOINT|CLOSE|CLUSTERED|COALESCE|COLLATE|COLUMN|COMMIT|COMPUTE|CONSTRAINT|CONTAINS|CONTAINSTABLE|CONTINUE|CONVERT|CREATE|CROSS|CURRENT|CURRENT_DATE|CURRENT_TIME|CURRENT_TIMESTAMP|CURRENT_USER|CURSOR|DATABASE|DBCC|DEALLOCATE|DECLARE|DEFAULT|DELETE|DENY|DESC|DISK|DISTINCT|DISTRIBUTED|DOUBLE|DROP|DUMMY|DUMP|ELSE|END|ERRLVL|ESCAPE|EXCEPT|EXEC|EXECUTE|EXISTS|EXIT|FETCH|FILE|FILLFACTOR|FOR|FOREIGN|FREETEXT|FREETEXTTABLE|FROM|FULL|FUNCTION|GOTO|GRANT|GROUP|HAVING|HOLDLOCK|IDENTITY|IDENTITYCOL|IDENTITY_INSERT|IF|IN|INDEX|INNER|INSERT|INTERSECT|INTO|IS|JOIN|KEY|KILL|LEFT|LIKE|LINENO|LOAD|NATIONAL|NOCHECK|NONCLUSTERED|NOT|NULL|NULLIF|OF|OFF|OFFSETS|ON|OPEN|OPENDATASOURCE|OPENQUERY|OPENROWSET|OPENXML|OPTION|OR|ORDER|OUTER|OVER|PERCENT|PLAN|PRECISION|PRIMARY|PRINT|PROC|PROCEDURE|PUBLIC|RAISERROR|READ|READTEXT|RECONFIGURE|REFERENCES|REPLICATION|RESTORE|RESTRICT|RETURN|REVOKE|RIGHT|ROLLBACK|ROWCOUNT|ROWGUIDCOL|RULE|SAVE|SCHEMA|SELECT|SESSION_USER|SET|SETUSER|SHUTDOWN|SOME|STATISTICS|SYSTEM_USER|TABLE|TEXTSIZE|THEN|TO|TOP|TRAN|TRANSACTION|TRIGGER|TRUNCATE|TSEQUAL|UNION|UNIQUE|UPDATE|UPDATETEXT|USE|USER|VALUES|VARYING|VIEW|WAITFOR|WHEN|WHERE|WHILE|WITH|WRITETEXT)(?=[^\w-]|$)/i,
null],[PR.PR_LITERAL,/^[+-]?(?:0x[\da-f]+|(?:(?:\.\d+|\d+(?:\.\d*)?)(?:e[+\-]?\d+)?))/i],[PR.PR_PLAIN,/^[a-z_][\w-]*/i],[PR.PR_PUNCTUATION,/^[^\w\t\n\r \xA0"'][^\w\t\n\r \xA0+\-"']*/]]),["sql"]);/*
 Copyright (C) 2015 Google Inc.
 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0
 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[ \n\r\t\v\f\0]+/,null," \n\r\t\v\f\x00"],[PR.PR_STRING,/^"(?:[^"\\]|(?:\\.)|(?:\\\((?:[^"\\)]|\\.)*\)))*"/,null,'"']],[[PR.PR_LITERAL,/^(?:(?:0x[\da-fA-F][\da-fA-F_]*\.[\da-fA-F][\da-fA-F_]*[pP]?)|(?:\d[\d_]*\.\d[\d_]*[eE]?))[+-]?\d[\d_]*/,null],[PR.PR_LITERAL,/^-?(?:(?:0(?:(?:b[01][01_]*)|(?:o[0-7][0-7_]*)|(?:x[\da-fA-F][\da-fA-F_]*)))|(?:\d[\d_]*))/,null],[PR.PR_LITERAL,/^(?:true|false|nil)\b/,null],[PR.PR_KEYWORD,/^\b(?:__COLUMN__|__FILE__|__FUNCTION__|__LINE__|associativity|as|break|case|class|continue|convenience|default|deinit|didSet|do|dynamic|dynamicType|else|enum|fallthrough|final|for|func|get|import|infix|init|inout|internal|if|in|is|lazy|left|let|mutating|none|nonmutating|operator|optional|override|postfix|precedence|prefix|private|protocol|Protocol|public|required|return|right|safe|self|set|static|struct|subscript|super|switch|Type|typealias|unowned|unsafe|var|weak|while|willSet)\b/,
null],[PR.PR_COMMENT,/^\/\/.*?[\n\r]/,null],[PR.PR_COMMENT,/^\/\*[\s\S]*?(?:\*\/|$)/,null],[PR.PR_PUNCTUATION,/^<<=|<=|<<|>>=|>=|>>|===|==|\.\.\.|&&=|\.\.<|!==|!=|&=|~=|~|\(|\)|\[|\]|{|}|@|#|;|\.|,|:|\|\|=|\?\?|\|\||&&|&\*|&\+|&-|&=|\+=|-=|\/=|\*=|\^=|%=|\|=|->|`|==|\+\+|--|\/|\+|!|\*|%|<|>|&|\||\^|\?|=|-|_/,null],[PR.PR_TYPE,/^\b(?:[@_]?[A-Z]+[a-z][A-Za-z_$@0-9]*|\w+_t\b)/,null]]),["swift"]);PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t\n\r \xA0\u2028\u2029]+/,null,"\t\n\r \u00a0\u2028\u2029"],[PR.PR_STRING,/^(?:["\u201C\u201D](?:[^"\u201C\u201D]|["\u201C\u201D]{2})(?:["\u201C\u201D]c|$)|["\u201C\u201D](?:[^"\u201C\u201D]|["\u201C\u201D]{2})*(?:["\u201C\u201D]|$))/i,null,'"\u201c\u201d'],[PR.PR_COMMENT,/^['\u2018\u2019][^\r\n\u2028\u2029]*/,null,"'\u2018\u2019"]],[[PR.PR_KEYWORD,/^(?:AddHandler|AddressOf|Alias|And|AndAlso|Ansi|As|Assembly|Auto|Boolean|ByRef|Byte|ByVal|Call|Case|Catch|CBool|CByte|CChar|CDate|CDbl|CDec|Char|CInt|Class|CLng|CObj|Const|CShort|CSng|CStr|CType|Date|Decimal|Declare|Default|Delegate|Dim|DirectCast|Do|Double|Each|Else|ElseIf|End|EndIf|Enum|Erase|Error|Event|Exit|Finally|For|Friend|Function|Get|GetType|GoSub|GoTo|Handles|If|Implements|Imports|In|Inherits|Integer|Interface|Is|Let|Lib|Like|Long|Loop|Me|Mod|Module|MustInherit|MustOverride|MyBase|MyClass|Namespace|New|Next|Not|NotInheritable|NotOverridable|Object|On|Option|Optional|Or|OrElse|Overloads|Overridable|Overrides|ParamArray|Preserve|Private|Property|Protected|Public|RaiseEvent|ReadOnly|ReDim|RemoveHandler|Resume|Return|Select|Set|Shadows|Shared|Short|Single|Static|Step|Stop|String|Structure|Sub|SyncLock|Then|Throw|To|Try|TypeOf|Unicode|Until|Variant|Wend|When|While|With|WithEvents|WriteOnly|Xor|EndIf|GoSub|Let|Variant|Wend)\b/i,
null],[PR.PR_COMMENT,/^REM[^\r\n\u2028\u2029]*/i],[PR.PR_LITERAL,/^(?:True\b|False\b|Nothing\b|\d+(?:E[+\-]?\d+[FRD]?|[FRDSIL])?|(?:&H[0-9A-F]+|&O[0-7]+)[SIL]?|\d*\.\d+(?:E[+\-]?\d+)?[FRD]?|#\s+(?:\d+[\-\/]\d+[\-\/]\d+(?:\s+\d+:\d+(?::\d+)?(\s*(?:AM|PM))?)?|\d+:\d+(?::\d+)?(\s*(?:AM|PM))?)\s+#)/i],[PR.PR_PLAIN,/^(?:(?:[a-z]|_\w)\w*|\[(?:[a-z]|_\w)\w*\])/i],[PR.PR_PUNCTUATION,/^[^\w\t\n\r "'\[\]\xA0\u2018\u2019\u201C\u201D\u2028\u2029]+/],[PR.PR_PUNCTUATION,/^(?:\[|\])/]]),["vb","vbs"]);PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"]],[[PR.PR_STRING,/^(?:[BOX]?"(?:[^"]|"")*"|'.')/i],[PR.PR_COMMENT,/^--[^\r\n]*/],[PR.PR_KEYWORD,/^(?:abs|access|after|alias|all|and|architecture|array|assert|attribute|begin|block|body|buffer|bus|case|component|configuration|constant|disconnect|downto|else|elsif|end|entity|exit|file|for|function|generate|generic|group|guarded|if|impure|in|inertial|inout|is|label|library|linkage|literal|loop|map|mod|nand|new|next|nor|not|null|of|on|open|or|others|out|package|port|postponed|procedure|process|pure|range|record|register|reject|rem|report|return|rol|ror|select|severity|shared|signal|sla|sll|sra|srl|subtype|then|to|transport|type|unaffected|units|until|use|variable|wait|when|while|with|xnor|xor)(?=[^\w-]|$)/i,
null],[PR.PR_TYPE,/^(?:bit|bit_vector|character|boolean|integer|real|time|string|severity_level|positive|natural|signed|unsigned|line|text|std_u?logic(?:_vector)?)(?=[^\w-]|$)/i,null],[PR.PR_TYPE,/^'(?:ACTIVE|ASCENDING|BASE|DELAYED|DRIVING|DRIVING_VALUE|EVENT|HIGH|IMAGE|INSTANCE_NAME|LAST_ACTIVE|LAST_EVENT|LAST_VALUE|LEFT|LEFTOF|LENGTH|LOW|PATH_NAME|POS|PRED|QUIET|RANGE|REVERSE_RANGE|RIGHT|RIGHTOF|SIMPLE_NAME|STABLE|SUCC|TRANSACTION|VAL|VALUE)(?=[^\w-]|$)/i,null],[PR.PR_LITERAL,/^\d+(?:_\d+)*(?:#[\w\\.]+#(?:[+\-]?\d+(?:_\d+)*)?|(?:\.\d+(?:_\d+)*)?(?:E[+\-]?\d+(?:_\d+)*)?)/i],
[PR.PR_PLAIN,/^(?:[a-z]\w*|\\[^\\]*\\)/i],[PR.PR_PUNCTUATION,/^[^\w\t\n\r \xA0"'][^\w\t\n\r \xA0\-"']*/]]),["vhdl","vhd"]);PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t \xA0a-gi-z0-9]+/,null,"\t \u00a0abcdefgijklmnopqrstuvwxyz0123456789"],[PR.PR_PUNCTUATION,/^[=*~\^\[\]]+/,null,"=*~^[]"]],[["lang-wiki.meta",/(?:^^|\r\n?|\n)(#[a-z]+)\b/],[PR.PR_LITERAL,/^(?:[A-Z][a-z][a-z0-9]+[A-Z][a-z][a-zA-Z0-9]+)\b/],["lang-",/^\{\{\{([\s\S]+?)\}\}\}/],["lang-",/^`([^\r\n`]+)`/],[PR.PR_STRING,/^https?:\/\/[^\/?#\s]*(?:\/[^?#\s]*)?(?:\?[^#\s]*)?(?:#\S*)?/i],[PR.PR_PLAIN,/^(?:\r\n|[\s\S])[^#=*~^A-Zh\{`\[\r\n]*/]]),["wiki"]);
PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_KEYWORD,/^#[a-z]+/i,null,"#"]],[]),["wiki.meta"]);PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PUNCTUATION,/^[:|>?]+/,null,":|>?"],[PR.PR_DECLARATION,/^%(?:YAML|TAG)[^#\r\n]+/,null,"%"],[PR.PR_TYPE,/^[&]\S+/,null,"&"],[PR.PR_TYPE,/^!\S*/,null,"!"],[PR.PR_STRING,/^"(?:[^\\"]|\\.)*(?:"|$)/,null,'"'],[PR.PR_STRING,/^'(?:[^']|'')*(?:'|$)/,null,"'"],[PR.PR_COMMENT,/^#[^\r\n]*/,null,"#"],[PR.PR_PLAIN,/^\s+/,null," \t\r\n"]],[[PR.PR_DECLARATION,/^(?:---|\.\.\.)(?:[\r\n]|$)/],[PR.PR_PUNCTUATION,/^-/],[PR.PR_KEYWORD,/^\w+:[ \r\n]/],[PR.PR_PLAIN,/^\w+/]]),
["yaml","yml"]);_ds.u(tJ,_ds.U);tJ.prototype.whenReady=function(){return this.L.promise};
tJ.prototype.connectedCallback=function(){var a=this,b;return _ds.D(function(c){switch(c.h){case 1:return _ds.v(c,DevsiteApp.whenReady(),2);case 2:return a.J||(vJ(a),uJ(a),a.J=!0),a.G.get("pref_dark-code")&&a.setAttribute("dark-code",""),a.L.resolve(),_ds.y(c,3),_ds.v(c,DevsiteApp.intersectionEnterForElement(a),5);case 5:_ds.A(c,4);break;case 3:if(b=_ds.B(c),"IntersectionObserver not supported"!==b.message)return c.return();case 4:var d=a.querySelector(".devsite-code-buttons-container");if(d)a.h=
d;else{a.h=_ds.Zp(oJ);a.hasAttribute("scope")&&(a.o=_ds.Zp(sJ,{label:"\u5728 JSFiddle \u4e2d\u958b\u555f\u7a0b\u5f0f\u78bc\u7bc4\u4f8b"}),(a.hasAttribute("jsfiddle-label")||a.hasAttribute("jsfiddle-title"))&&a.o.setAttribute("data-label",a.getAttribute("jsfiddle-label")||a.getAttribute("jsfiddle-title")),a.h.appendChild(a.o));a.C=_ds.Zp(pJ,{label:"\u6df1\u8272\u7a0b\u5f0f\u78bc\u4e3b\u984c"});a.h.appendChild(a.C);a.D=_ds.Zp(qJ,{label:"\u6dfa\u8272\u7a0b\u5f0f\u78bc\u4e3b\u984c"});a.h.appendChild(a.D);
if(!a.hasAttribute("no-copy")){d=a.getAttribute("data-copy-event-label");var f="Click To Copy";d&&(f+=": "+d);a.m=_ds.Zp(rJ,{label:a.H,Nl:f});a.h.appendChild(a.m)}a.prepend(a.h)}xJ(a);a.F=document.querySelector("devsite-snackbar");_ds.x(c)}})};tJ.prototype.disconnectedCallback=function(){var a=this;return _ds.D(function(b){if(1==b.h)return _ds.v(b,DevsiteApp.whenReady(),2);DevsiteApp.unregisterIntersectionForElement(a);a.h&&a.removeChild(a.h);_ds.Rj(a.j);_ds.x(b)})};
tJ.prototype.attributeChangedCallback=function(a,b,c){var d=this;return _ds.D(function(f){if(1==f.h){if("dark-code"!==a||b===c)return f.K(0);if(d.hasAttribute("dark-code"))return d.G.set("pref_dark-code","1"),_ds.v(f,_ds.Ji(),6);d.G.remove("pref_dark-code");return _ds.v(f,_ds.Ji(),5)}if(6!=f.h)return Array.from(document.querySelectorAll("devsite-code[dark-code]")).forEach(function(g){g.removeAttribute("dark-code")}),f.K(0);Array.from(document.querySelectorAll("devsite-code:not([dark-code])")).filter(function(g){return g!==
d}).forEach(function(g){g.setAttribute("dark-code","")});_ds.x(f)})};_ds.n.Object.defineProperties(tJ,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return["dark-code"]}}});tJ.prototype.attributeChangedCallback=tJ.prototype.attributeChangedCallback;tJ.prototype.disconnectedCallback=tJ.prototype.disconnectedCallback;tJ.prototype.connectedCallback=tJ.prototype.connectedCallback;tJ.prototype.whenReady=tJ.prototype.whenReady;try{window.customElements.define("devsite-code",tJ)}catch(a){console.warn("devsite.app.customElement.DevsiteCode",a)};})(_ds_www);
