(function(_ds){var window=this;'use strict';var HJ=function(){var a=_ds.U.call(this)||this;a.o=new _ds.Lj;a.C=new _ds.Lj;a.j=new Set;a.h=null;"IntersectionObserver"in window&&(a.h=new IntersectionObserver(function(b){b=_ds.t(b);for(var c=b.next();!c.done;c=b.next())c=c.value,c.isIntersecting&&(c=c.target,_ds.Ps(new _ds.Ns,c),a.j.delete(c),a.h.unobserve(c))},{rootMargin:"100%"}));return a},IJ=function(a){Array.from(a.getElementsByTagName("table")).forEach(function(b){if(!b.parentNode.classList.contains("devsite-table-wrapper")){var c=
document.createElement("div");c.classList.add("devsite-table-wrapper");b.classList.contains("full-width")&&(c.classList.add("devsite-full-width-table"),b.classList.remove("full-width"));_ds.Wg(c,b);c.appendChild(b)}})},QJ=function(a,b){var c,d,f,g,k,l,m;return _ds.D(function(p){if(1==p.h)return _ds.v(p,DevsiteApp.whenReady(),2);c=_ds.ui();d=DevsiteApp.getInsecureHost();f=b.Z;if(f.origin!==c.origin&&d&&f.origin!==d)return p.return();try{g=_ds.Gf(_ds.Ck,f.data)}catch(q){return p.return()}k=_ds.qf(g,
1,0);if(4===k)return JJ(a,f),p.return();l=g.getName();if(!l)return p.return();if(m=a.querySelector('devsite-iframe iframe[name="'+l+'"]'))switch(k){case 5:KJ(g,m);break;case 8:LJ(f,g,c);break;case 1:MJ(f,g,c);break;case 6:case 7:NJ(k,c,g);break;case 9:OJ(a,g);break;case 10:PJ(g,c)}_ds.x(p)})},KJ=function(a,b){var c,d,f,g;_ds.D(function(k){c=_ds.Ng(document).y;d=_ds.rf(a,4);f=_ds.rf(a,3);g=_ds.gh(b);d&&g.setAttribute("width",d+"px");f&&g.setAttribute("height",f+"px");window.requestAnimationFrame(function(){window.scrollTo(_ds.Ng(document).x,
c)});_ds.x(k)})},JJ=function(a,b){var c,d,f;_ds.D(function(g){if(c=RJ(a,b.source)){d="goog_"+_ds.Nk++;c.setAttribute("name",d);var k=_ds.Dk(3);f=_ds.R(k,2,d);(k=b.source)&&k.postMessage(f.Ha(),"*")}_ds.x(g)})},LJ=function(a,b,c){var d;_ds.D(function(f){var g=_ds.Ek(_ds.Dk(8),_ds.O(b,8));d=_ds.R(g,6,c.toString());(g=a.source)&&g.postMessage(d.Ha(),"*");_ds.x(f)})},MJ=function(a,b,c){var d;_ds.D(function(f){var g=_ds.Ek(_ds.Dk(2),_ds.O(b,8));d=_ds.R(g,7,c.search+c.hash);(g=a.source)&&g.postMessage(d.Ha(),
"*");_ds.x(f)})},NJ=function(a,b,c){var d,f,g;_ds.D(function(k){d=c.Ea();f=new URL(c.getUrl(),b.origin);g=window.location.origin+window.location.pathname+f.search+f.hash;6===a?window.history.pushState({},d,g):window.history.replaceState({},d,g);_ds.x(k)})},OJ=function(a,b){var c,d,f,g;_ds.D(function(k){c=_ds.O(b,9);d=JSON.parse(_ds.O(b,10));"cloudtrackEvent"===c&&d?(f=d,g={eventData:f},a.dispatchEvent(new CustomEvent("devsite-analytics-observation-cloudtrack",{detail:g,bubbles:!0}))):"devsite-apix"===
c&&a.dispatchEvent(new CustomEvent("devsite-apix-observation",{detail:d,bubbles:!0}));_ds.x(k)})},PJ=function(a,b){var c,d;_ds.D(function(f){if(c=a.getUrl())d=new URL(c,b.origin),c.startsWith("#")||b.origin===d.origin&&b.pathname===d.pathname&&b.search===d.search?DevsiteApp.scrollToAnchor(d.hash,!0):DevsiteApp.fetchPage(d.href);_ds.x(f)})},RJ=function(a,b){var c;Array.from(a.querySelectorAll("devsite-iframe iframe")).forEach(function(d){_ds.kh(d)===b&&(c=d)});return c},UJ=function(a){a.m=a.querySelector(".devsite-article-body");
a.m&&SJ(a);a.h&&a.h.disconnect();a.j.clear();IJ(a);var b=Array.from(a.querySelectorAll(".devsite-nav-title, td > code, th > code"));a.j.clear();a.j=new Set(b);if(_ds.ui().hash){b=new _ds.Ns;for(var c=_ds.t(a.j),d=c.next();!d.done;d=c.next())_ds.Ps(b,d.value)}else TJ(a,a.j);a.dispatchEvent(new CustomEvent("devsite-content-updated",{bubbles:!0}))},SJ=function(a){"full"===document.body.getAttribute("layout")&&(a=a.m.querySelectorAll('h1[tabindex="0"],h2[tabindex="0"],h3[tabindex="0"],h4[tabindex="0"],h5[tabindex="0"],h6[tabindex="0"]'))&&
Array.from(a).forEach(function(b){b.removeAttribute("tabindex")})},TJ=function(a,b){a.h&&b.forEach(function(c){a.h.observe(c)})};_ds.u(HJ,_ds.U);HJ.prototype.connectedCallback=function(){var a=this;this.o.listen(window,"message",function(b){return QJ(a,b)});UJ(this)};HJ.prototype.disconnectedCallback=function(){this.h&&this.h.disconnect();this.j.clear();_ds.Rj(this.o);_ds.Rj(this.C)};
HJ.prototype.updateContent=function(a){var b=this;a&&([".devsite-article","devsite-content-footer","devsite-google-survey"].forEach(function(c){_ds.Al(b,b.querySelector(c),a.querySelector(c))}),UJ(this))};HJ.prototype.updateContent=HJ.prototype.updateContent;HJ.prototype.disconnectedCallback=HJ.prototype.disconnectedCallback;HJ.prototype.connectedCallback=HJ.prototype.connectedCallback;try{window.customElements.define("devsite-content",HJ)}catch(a){console.warn("devsite.app.customElement.DevsiteContent",a)};})(_ds_www);
